# 1. IMPORTAR LIBRERÍAS/CONFIGURACIÓN

In [8]:
import pandas as pd
import numpy as np
import requests as req
from selenium import webdriver
from bs4 import BeautifulSoup as bs
from time import sleep
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

In [9]:
!apt-get update
!apt install chromium-chromedriver

"apt-get" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"apt" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

In [10]:
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()

from selenium.webdriver.common.keys import Keys

In [11]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support.ui import Select
import time
import random

In [12]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

In [6]:
# Crea un objeto Options
options = Options()

# Configura las opciones según sea necesario
#options.add_argument('--headless')  # Si deseas ejecutar en modo headless
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

browser = webdriver.Chrome(options=options)

Get html/url & Acceptar cookies

In [7]:
url = "https://www.airbnb.es/s/Palma-de-Mallorca--Palma--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&price_filter_input_type=0&channel=EXPLORE&query=Palma%20de%20Mallorca%2C%20Palma%2C%20Espa%C3%B1a&place_id=ChIJ5211TJyTlxIRylgC_aC43po&date_picker_type=calendar&source=structured_search_input_header&search_type=filter_change&search_mode=regular_search&price_filter_num_nights=15"

In [8]:
browser.get(url)

In [9]:
url

'https://www.airbnb.es/s/Palma-de-Mallorca--Palma--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&price_filter_input_type=0&channel=EXPLORE&query=Palma%20de%20Mallorca%2C%20Palma%2C%20Espa%C3%B1a&place_id=ChIJ5211TJyTlxIRylgC_aC43po&date_picker_type=calendar&source=structured_search_input_header&search_type=filter_change&search_mode=regular_search&price_filter_num_nights=15'

In [10]:
# Aceptar cookies
button_cookies = browser.find_element(by=By.XPATH, value="/html/body/div[5]/div/div/div[1]/div/div[5]/section/div[2]/div[2]/button")

button_cookies.click()
time.sleep(5)
print("Cookies aceptadas")

Cookies aceptadas

Web-Scraping de 1 elemento (una casa)

In [11]:
url_room = "https://www.airbnb.es/rooms/1114500207597778842?adults=1&category_tag=Tag%3A8678&children=0&enable_m3_private_room=true&infants=0&pets=0&photo_id=1863149920&check_in=2024-04-29&check_out=2024-05-04&source_impression_id=p3_1711647328_cNYQumyj79tEVJtZ&previous_page_section_name=1000&federated_search_id=e9ca0384-0e97-466d-8f08-1a04f240e85a"

browser.get(url_room)
time.sleep(3)

In [12]:
#Cerrar ventana
button_x = browser.find_element(by=By.XPATH, value="/html/body/div[9]/div/div/section/div/div/div[2]/div/div[1]/button")

button_x.click()
time.sleep(3)
print("Ventana cerrada")

Ventana cerrada

In [13]:
html = browser.page_source
html

'<html lang="es" dir="ltr" data-is-hyperloop="true" data-hyperloop-version="2" class="scrollbar-gutter g5l85gq dir native v1oc6b3k vgnbcm1 v1agkal2 vqw89vp vlugpmm" style="--vh: 6.51px; --vw: 9.96px; --vw-unitless: 996;"><head><meta charset="utf-8"><meta name="locale" content="es"><meta name="google" content="notranslate"><meta id="csrf-param-meta-tag" name="csrf-param" content="authenticity_token"><meta id="csrf-token-meta-tag" name="csrf-token" content="null"><meta id="english-canonical-url" content=""><meta name="twitter:widgets:csp" content="on"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="application-name" content="Airbnb"><meta name="apple-mobile-web-app-title" content="Airbnb"><meta name="theme-color" content="#ffffff"><meta name="msapplication-navbutton-color" content="#ffffff"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="msapplication-starturl" content="/?utm_source=homescreen"><link href="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/apps/core-guest-spa/client.59c879a3ee.css" rel="stylesheet" type="text/css" media="all" crossorigin="anonymous"><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-788919195&amp;l=dataLayer&amp;cx=c"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-2P6Q8PGG16&amp;l=dataLayer&amp;cx=c"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/destination?id=G-2P6Q8PGG16&amp;l=dataLayer&amp;cx=c"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/destination?id=DC-4620401&amp;l=dataLayer&amp;cx=c"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-1023009977&amp;l=dataLayer&amp;cx=c"></script><script defer="" src="https://www.googletagmanager.com/gtm.js?id=GTM-46MK"></script><script src="https://connect.facebook.net/es_ES/sdk.js?hash=7ecf98318d1a473ff093eadec0765301" async="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/metroRequire.ae703c8f7e.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/shims_post_modules.3a508a05ae.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/airmetro/src/browser/asyncRequire.5a5f8a923f.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/coreV2.d6f9f63d25.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/routeHandler.eb80466977.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/4199.4500ef2920.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/6c27.4feaf83dff.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/8bc1.e357790ef0.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/10f8.9117338e7d.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/node_modules/moment/locale/es.2078639028.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/apps/core-guest-spa/initializer.c6c1050f75.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/guest-header/query/HeaderQuery.prepare.d7f2b63b5c.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/08bb.14cb15ead3.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/348c.a419a85714.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/niobe/minimalist/index.e2c6bf6af5.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/5ab1.3c4a4b9cb9.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/ab3c.4c565ae1fd.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/8bdd.a877735f0e.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/215b.45a018a6e8.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/1a9c.a1bd5018d3.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/ee00.ff9847e789.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/3ccd.c8194e5b79.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/0d90.ade6c80b29.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/28bf.31bec2cd3d.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/gp-stays-pdp-route/routes/PdpPlatformRoute.731fbc50ad.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/gp-stays-pdp-route/routes/PdpPlatformRouteSkeleton.prepare.f801ef77ef.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/f4c9f.a8028461f8.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/0f40.6d823b63ed.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/a2ec.121a9da08c.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/4857.55b4640d65.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/e008.fe6a320ca9.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/e3a3.8014d0c86b.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/1cc0.9a9004ba18.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/2b64.48dfb6f865.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/ee94.dd2a6387c0.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/core-guest-loop/apps/core-guest-spa/client.032711faf6.js" defer="" crossorigin="anonymous"></script><script>(function() {\n  // pg_pixel is no-op now.\n})()</script><script>(function(){function a(c){if(window._errorReportingInitialized)return void window.removeEventListener("error",a);const{error:d}=c;if(!d)return;const e=c.message||d.message,f=/Requiring unknown module/.test(e)?1/100:1/10;if(Math.random()>f)return;const{locale:g,tracking_context:h}=window[Symbol.for("__ global cache key __")]?.["string | airbnb-bootstrap-data"]?.["_bootstrap-layout-init"]??{},i=g||navigator.language,j=location.pathname,k="undefined"==typeof window?{sampleRate:f+""}:{tags:{loggingSource:"browser",sampleRate:f+""}};fetch("https://notify.bugsnag.com/",{headers:{"Bugsnag-Payload-Version":"5"},body:JSON.stringify({apiKey:"e393bc25e52fe915ffb56c14ddf2ff1b",payloadVersion:b,notifier:{name:"Bugsnag JavaScript",version:"0.0.5-AirbnbUnhandledBufferedErrorCustomFetch",url:""},events:[{exceptions:[{errorClass:d.name,message:e,stacktrace:[{file:c.filename,lineNumber:c.lineno,columnNumber:c.colno}],type:"browserjs"}],request:{url:location.href},context:j,groupingHash:d.name.concat("-",e,"-",j),unhandled:!0,app:{releaseStage:h?.environment},device:{time:new Date,userAgent:navigator.userAgent},metaData:{infra:{app_name:h?.app,is_buffered_error:!0,loop_name:h?.controller,locale:i,service_worker_url:navigator.serviceWorker?.controller?.scriptURL},...k}}]}),method:"POST"})}const b="5";"undefined"!=typeof window&&window.addEventListener("error",a)})();</script><script>\n// FID init code.\n(function(a,b){function c(a){l.push(a),f()}function d(a,b){i||(i=b,j=a,k=new Date,f())}function e(){i&&(i=null,j=null,k=null)}function f(){0<=j&&j<k-n&&(l.forEach(a=>{a(j,i)}),l=[])}function g(c,e){function f(){d(c,e),h()}function g(){h()}function h(){b(o,f,m),b(p,g,m)}a(o,f,m),a(p,g,m)}function h(a){if(a.cancelable){const b=1e12<a.timeStamp,c=b?new Date:performance.now(),e=c-a.timeStamp;"pointerdown"===a.type?g(e,a):d(e,a)}}let i,j,k,l=[];const m={passive:!0,capture:!0},n=new Date,o="pointerup",p="pointercancel";(function(a){["click","mousedown","keydown","touchstart","pointerdown"].forEach(b=>{a(b,h,m)})})(a),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=c,self.perfMetrics.clearFirstInputDelay=e})(addEventListener,removeEventListener);\n// TTFMP Polyfill code.\n(function(a){function b(){const c=document.getElementById(i);h=0,c?g===c?e=a(b):"IMG"!==c.tagName||c.complete?a(function(){const a=performance.now();g=c,f?f(a):h=a,performance.measure&&performance.measure("TTFMP")}):e=a(b):e=a(b)}function c(a){h?a(h):f=a}function d(){cancelAnimationFrame(e)}let e,f,g,h;const i="FMP-target";e=a(b),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstMeaningfulPaint=c,self.perfMetrics.startSearchingForFirstMeaningfulPaint=function(){g=document.getElementById(i),b()},self.perfMetrics.stopSearchingForFirstMeaningfulPaint=d})(requestAnimationFrame);\n// LCP Polyfill code\n(function(a,b,c){function d(a,b,c){(b>o*(1+q)||!document.body.contains(m))&&(o=b,p=c,m=a,x?.(p,m,o))}function e(a,b){if("IMG"!==a.tagName)b();else{const d=()=>c(b);a.complete?d():a.addEventListener("load",d,{once:!0})}}function f(a){w?.observe(a)}function g(a){return u.includes(a.tagName)||a.hasAttribute("data-lcp-candidate")}function h(){if(t)if(s)v||(v={IMG:document.getElementsByTagName("img"),H1:document.getElementsByTagName("h1"),H2:document.getElementsByTagName("h2"),H3:document.getElementsByTagName("h3"),H4:document.getElementsByTagName("h4"),H5:document.getElementsByTagName("h5"),SVG:document.getElementsByTagName("svg")}),u.forEach(a=>{Array.from(v[a]).forEach(a=>{f(a)})}),setTimeout(h,50);else{!r&&document.body&&(r=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,a=>g(a)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT));for(let a;a=r?.nextNode();)f(a);c(h)}}function i(){n=performance.now(),o=0,p=0,w=new IntersectionObserver(a=>{a.filter(a=>a.isIntersecting).forEach(a=>{const b=a.target,{width:c,height:f}=a.intersectionRect;e(b,()=>{const a=performance.now();d(b,c*f,a)})})}),c(h),y.forEach(b=>{a(b,j,z)})}function j(a){const b=a.target;"scroll"===a.type&&("expand-trigger"===b?.className||"contract-trigger"===b?.className)||0===o||250>performance.now()-n||k()}function k(){w?.disconnect(),y.forEach(a=>{b(a,j,z)}),t=!1,w=null}function l(a){x=a,0!==p&&x(p,m,o)}let m,n=0,o=0,p=0;const q=666778e-9;let r,s=!1,t=!0;const u=["IMG","H1","H2","H3","H4","H5","SVG"];let v,w,x;const y=["click","mousedown","keydown","touchstart","pointerdown","scroll"],z={passive:!0,capture:!0};i(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onLargestContentfulPaint=l,self.perfMetrics.startSearchingForLargestContentfulPaint=i.bind(null,!1),self.perfMetrics.stopSearchingForLargestContentfulPaint=k,self.perfMetrics.markIsHydratedForLargestContentfulPaint=()=>{s=!0},self.perfMetrics.registerLCPCandidate=f,self.perfMetrics.inspectLCPTarget=()=>m})(addEventListener,removeEventListener,requestAnimationFrame);\n// INP init code.\n(function(a){var b=Math.max,c=Math.min;function d(){return null==t?null==performance.interactionCount?0:performance.interactionCount:u}function e(){const a=d()-n;return a}function f(){const a=c(r.length-1,Math.floor(e()/50));return r[a]}function g(){"PerformanceObserver"in window&&PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("event")&&(y(),m=new PerformanceObserver(a=>{Promise.resolve().then(()=>{const b=a.getEntries();i(b)})}),m.observe({type:"event",buffered:!0,durationThreshold:40}),m.observe({type:"first-input",buffered:!0}),a("visibilitychange",j,!0),a("pageshow",k,!0))}function h(a){if(null==a.interactionId)return;const c=r[r.length-1],d=s.get(a.interactionId);if(null!=d||r.length<q||a.duration>c.latency){if(null!=d)d.entries.push(a),d.latency=b(d.latency,a.duration);else{const b={id:a.interactionId,latency:a.duration,entries:[a]};r.push(b),s.set(a.interactionId,b)}r.sort((c,a)=>a.latency-c.latency),r.splice(q).forEach(a=>{s.delete(a.id)})}}function i(a){a.forEach(a=>{a.interactionId&&h(a)});const b=f();b&&b.latency!==o.value&&(o.value=b.latency,o.entries=b.entries,l())}function j(){null==m||"hidden"===document.visibilityState&&(i(m.takeRecords()),0>o.value&&0<e()&&(o.value=0,o.entries=[]),l())}function k(a){a.persisted&&(r=[],s.clear(),n=d(),o.value=-1,o.entries=[])}function l(){p&&p(o.value,o.entries)}let m,n=0;const o={value:-1,entries:[]};let p;const q=10;let r=[];const s=new Map;let t,u=0,v=1/0,w=0;const x=a=>{a.forEach(a=>{a.interactionId&&(v=c(v,a.interactionId),w=b(w,a.interactionId),u=w?(w-v)/7+1:0)})},y=()=>{"interactionCount"in performance||null!=t||PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("event")&&(t=new PerformanceObserver(a=>{Promise.resolve().then(()=>{x(a.getEntries())})}),t.observe({type:"event",buffered:!0,durationThreshold:0}))};g(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onInp=function(a){0<=o.value?a(o.value,o.entries):p=a},self.perfMetrics.clearInp=function(){r=[],s.clear(),n=0,u=0,v=1/0,w=0,o.value=-1,o.entries=[]}})(addEventListener);\n</script><script>((a,b,c,d)=>{if(d.supports("(font: -apple-system-body) and (-webkit-touch-callout: default)")){const d=a.createElement("div");d.setAttribute("style","font: -apple-system-body"),b.appendChild(d);const e=c(d);"17px"===e.fontSize&&b.style.setProperty("font-size","16px"),b.removeChild(d)}})(document,document.documentElement,getComputedStyle,CSS);</script><link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="Airbnb"><link rel="apple-touch-icon" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-76x76-3b313d93b1b5823293524b9764352ac9.png"><link rel="apple-touch-icon" sizes="76x76" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-76x76-3b313d93b1b5823293524b9764352ac9.png"><link rel="apple-touch-icon" sizes="120x120" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-120x120-52b1adb4fe3a8f825fc4b143de12ea4b.png"><link rel="apple-touch-icon" sizes="152x152" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-152x152-7b7c6444b63d8b6ebad9dae7169e5ed6.png"><link rel="apple-touch-icon" sizes="180x180" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-180x180-bcbe0e3960cd084eb8eaf1353cf3c730.png"><link rel="icon" sizes="192x192" href="https://a0.muscache.com/airbnb/static/icons/android-icon-192x192-c0465f9f0380893768972a31a614b670.png"><link rel="shortcut icon" sizes="76x76" type="image/x-icon" href="https://a0.muscache.com/airbnb/static/logotype_favicon-21cc8e6c6a2cca43f061d2dcabdf6e58.ico"><link rel="mask-icon" href="https://a0.muscache.com/airbnb/static/icons/airbnb-0611901eac33ccfa5e93d793a2e21f09.svg" color="#FF5A5F"><link href="https://a0.muscache.com/airbnb/static/packages/dls/dls-lite_cereal-47d27fa833e062fe3413637eb751001f.css" rel="stylesheet" type="text/css" media="all" crossorigin="anonymous"><meta content="width=device-width, initial-scale=1, viewport-fit=cover" name="viewport"><style data-aphrodite="true" id="aphrodite" type="text/css">._9r8p20{color:#222222 !important;font-family:Circular,-apple-system,BlinkMacSystemFont,Roboto,Helvetica Neue,sans-serif !important;font-weight:400 !important;font-size:1rem !important;line-height:1.25rem !important;--gp-section-compact-padding:32px !important;--gp-section-compact-padding-condensed:16px !important;--gp-section-standard-padding:48px !important;--gp-section-standard-padding-condensed:24px !important;}._1k81gub{position:relative !important;}@supports (height: 1dvh){._1k81gub{min-height:100dvh !important;}}@supports not (height: 1dvh){._1k81gub{min-height:-webkit-calc(100 * var(--vh) - env(safe-area-inset-bottom, 0px)) !important;min-height:-moz-calc(100 * var(--vh) - env(safe-area-inset-bottom, 0px)) !important;min-height:calc(100 * var(--vh) - env(safe-area-inset-bottom, 0px)) !important;}}._siy8gh{display:none !important;}@media (min-width: 744px){._siy8gh{display:block !important;}}._vuzcgs{-webkit-box-pack:end !important;-ms-flex-pack:end !important;-webkit-box-align:center !important;-ms-flex-align:center !important;position:relative !important;display:-webkit-box !important;display:-moz-box !important;display:-ms-flexbox !important;display:-webkit-flex !important;display:flex !important;-webkit-align-items:center !important;align-items:center !important;-webkit-justify-content:flex-end !important;justify-content:flex-end !important;height:80px !important;}._176ugpa{-webkit-box-pack:end !important;-ms-flex-pack:end !important;display:-webkit-box !important;display:-moz-box !important;display:-ms-flexbox !important;display:-webkit-flex !important;display:flex !important;-webkit-flex:auto !important;-ms-flex:1 1 auto !important;flex:auto !important;-webkit-justify-content:flex-end !important;justify-content:flex-end !important;margin-right:8px !important;}._pvfq6t{position:relative !important;display:inline-block !important;vertical-align:middle !important;margin-top:auto !important;margin-bottom:auto !important;}._z5mecy{-webkit-box-align:center !important;-ms-flex-align:center !important;-webkit-align-items:center !important;align-items:center !important;display:-webkit-box !important;display:-moz-box !important;display:-ms-flexbox !important;display:-webkit-flex !important;display:flex !important;height:18px !important;position:relative !important;z-index:1 !important;}._167wsvl{display:inline !important;position:relative !important;}._88xxct{display:none !important;}@media print{._88xxct{display:block !important;}}@media (min-width: 744px){._88xxct{display:block !important;}}._1a6d9c4{-webkit-box-lines:multiple !important;-webkit-box-pack:start !important;-ms-flex-pack:start !important;-webkit-box-align:stretch !important;-ms-flex-align:stretch !important;display:-webkit-box !important;display:-moz-box !important;display:-ms-flexbox !important;display:-webkit-flex !important;display:flex !important;-webkit-align-items:stretch !important;align-items:stretch !important;-webkit-justify-content:flex-start !important;justify-content:flex-start !important;-webkit-flex-wrap:wrap !important;-ms-flex-wrap:wrap !important;flex-wrap:wrap !important;width:100% !important;padding-left:var(--gp-padding-xsmallAndAbove, 24px) !important;padding-right:var(--gp-padding-xsmallAndAbove, 24px) !important;margin-left:0px !important;margin-right:0px !important;}@media (min-width: 375px){._1a6d9c4{padding-left:var(--gp-padding-smallAndAbove, 24px) !important;padding-right:var(--gp-padding-smallAndAbove, 24px) !important;}}@media (min-width: 744px){._1a6d9c4

In [14]:
soup = bs(html, 'lxml')
soup

<html class="scrollbar-gutter g5l85gq dir native v1oc6b3k vgnbcm1 v1agkal2 vqw89vp vlugpmm" data-hyperloop-version="2" data-is-hyperloop="true" dir="ltr" lang="es" style="--vh: 6.51px; --vw: 9.96px; --vw-unitless: 996;"><head><meta charset="utf-8"/><meta content="es" name="locale"/><meta content="notranslate" name="google"/><meta content="authenticity_token" id="csrf-param-meta-tag" name="csrf-param"/><meta content="null" id="csrf-token-meta-tag" name="csrf-token"/><meta content="" id="english-canonical-url"/><meta content="on" name="twitter:widgets:csp"/><meta content="yes" name="mobile-web-app-capable"/><meta content="yes" name="apple-mobile-web-app-capable"/><meta content="Airbnb" name="application-name"/><meta content="Airbnb" name="apple-mobile-web-app-title"/><meta content="#ffffff" name="theme-color"/><meta content="#ffffff" name="msapplication-navbutton-color"/><meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"/><meta content="/?utm_source=homescreen" name="msapplication-starturl"/><link crossorigin="anonymous" href="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/apps/core-guest-spa/client.59c879a3ee.css" media="all" rel="stylesheet" type="text/css"/><script async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-788919195&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-2P6Q8PGG16&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/destination?id=G-2P6Q8PGG16&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/destination?id=DC-4620401&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-1023009977&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script defer="" src="https://www.googletagmanager.com/gtm.js?id=GTM-46MK"></script><script async="" crossorigin="anonymous" src="https://connect.facebook.net/es_ES/sdk.js?hash=7ecf98318d1a473ff093eadec0765301"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/metroRequire.ae703c8f7e.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/shims_post_modules.3a508a05ae.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/airmetro/src/browser/asyncRequire.5a5f8a923f.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/coreV2.d6f9f63d25.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/routeHandler.eb80466977.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/4199.4500ef2920.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/6c27.4feaf83dff.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/8bc1.e357790ef0.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/10f8.9117338e7d.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/node_modules/moment/locale/es.2078639028.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/apps/core-guest-spa/initializer.c6c1050f75.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/guest-header/query/HeaderQuery.prepare.d7f2b63b5c.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/08bb.14cb15ead3.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/348c.a419a85714.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/niobe/minimalist/index.e2c6bf6af5.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/5ab1.3c4a4b9cb9.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/ab3c.4c565ae1fd.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/8bdd.a877735f0e.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/215b.45a018a6e8.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/1a9c.a1bd5018d3.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/ee00.ff9847e789.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/3ccd.c8194e5b79.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/0d90.ade6c80b29.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/28bf.31bec2cd3d.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/gp-stays-pdp-route/routes/PdpPlatformRoute.731fbc50ad.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/gp-stays-pdp-route/routes/PdpPlatformRouteSkeleton.prepare.f801ef77ef.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/f4c9f.a8028461f8.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/0f40.6d823b63ed.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/a2ec.121a9da08c.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/4857.55b4640d65.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/e008.fe6a320ca9.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/e3a3.8014d0c86b.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/1cc0.9a9004ba18.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/2b64.48dfb6f865.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/ee94.dd2a6387c0.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/core-guest-loop/apps/core-guest-spa/client.032711faf6.js"></script><script>(function() {
  // pg_pixel is no-op now.
})()</script><script>(function(){function a(c){if(window._errorReportingInitialized)return void window.removeEventListener("error",a);const{error:d}=c;if(!d)return;const e=c.message||d.message,f=/Requiring unknown module/.test(e)?1/100:1/10;if(Math.random()>f)return;const{locale:g,tracking_context:h}=window[Symbol.for("__ global cache key __")]?.["string | airbnb-bootstrap-data"]?.["_bootstrap-layout-init"]??{},i=g||navigator.language,j=location.pathname,k="undefined"==typeof window?{sampleRate:f+""}:{tags:{loggingSource:"browser",sampleRate:f+""}};fetch("https://notify.bugsnag.com/",{headers:{"Bugsnag-Payload-Version":"5"},body:JSON.stringify({apiKey:"e393bc25e52fe915ffb56c14ddf2ff1b",payloadVersion:b,notifier:{name:"Bugsnag JavaScript",version:"0.0.5-AirbnbUnhandledBufferedErrorCustomFetch",url:""},events:[{exceptions:[{errorClass:d.name,message:e,stacktrace:[{file:c.filename,lineNumber:c.lineno,columnNumber:c.colno}],type:"browserjs"}],request:{url:location.href},context:j,groupingHash:d.name.concat("-",e,"-",j),unhandled:!0,app:{releaseStage:h?.environment},device:{time:new Date,userAgent:navigator.userAgent},metaData:{infra:{app_name:h?.app,is_buffered_error:!0,loop_name:h?.controller,locale:i,service_worker_url:navigator.serviceWorker?.controller?.scriptURL},...k}}]}),method:"POST"})}const b="5";"undefined"!=typeof window&&window.addEventListener("error",a)})();</script><script>
// FID init code.
(function(a,b){function c(a){l.push(a),f()}function d(a,b){i||(i=b,j=a,k=new Date,f())}function e(){i&&(i=null,j=null,k=null)}function f(){0<=j&&j<k-n&&(l.forEach(a=>{a(j,i)}),l=[])}function g(c,e){function f(){d(c,e),h()}function g(){h()}function h(){b(o,f,m),b(p,g,m)}a(o,f,m),a(p,g,m)}function h(a){if(a.cancelable){const b=1e12<a.timeStamp,c=b?new Date:performance.now(),e=c-a.timeStamp;"pointerdown"===a.type?g(e,a):d(e,a)}}let i,j,k,l=[];const m={passive:!0,capture:!0},n=new Date,o="pointerup",p="pointercancel";(function(a){["click","mousedown","keydown","touchstart","pointerdown"].forEach(b=>{a(b,h,m)})})(a),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=c,self.perfMetrics.clearFirstInputDelay=e})(addEventListener,removeEventListener);
// TTFMP Polyfill code.
(function(a){function b(){const c=document.getElementById(i);h=0,c?g===c?e=a(b):"IMG"!==c.tagName||c.complete?a(function(){const a=performance.now();g=c,f?f(a):h=a,performance.measure&&performance.measure("TTFMP")}):e=a(b):e=a(b)}function c(a){h?a(h):f=a}function d(){cancelAnimationFrame(e)}let e,f,g,h;const i="FMP-target";e=a(b),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstMeaningfulPaint=c,self.perfMetrics.startSearchingForFirstMeaningfulPaint=function(){g=document.getElementById(i),b()},self.perfMetrics.stopSearchingForFirstMeaningfulPaint=d})(requestAnimationFrame);
// LCP Polyfill code
(function(a,b,c){function d(a,b,c){(b>o*(1+q)||!document.body.contains(m))&&(o=b,p=c,m=a,x?.(p,m,o))}function e(a,b){if("IMG"!==a.tagName)b();else{const d=()=>c(b);a.complete?d():a.addEventListener("load",d,{once:!0})}}function f(a){w?.observe(a)}function g(a){return u.includes(a.tagName)||a.hasAttribute("data-lcp-candidate")}function h(){if(t)if(s)v||(v={IMG:document.getElementsByTagName("img"),H1:document.getElementsByTagName("h1"),H2:document.getElementsByTagName("h2"),H3:document.getElementsByTagName("h3"),H4:document.getElementsByTagName("h4"),H5:document.getElementsByTagName("h5"),SVG:document.getElementsByTagName("svg")}),u.forEach(a=>{Array.from(v[a]).forEach(a=>{f(a)})}),setTimeout(h,50);else{!r&&document.body&&(r=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,a=>g(a)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT));for(let a;a=r?.nextNode();)f(a);c(h)}}function i(){n=performance.now(),o=0,p=0,w=new IntersectionObserver(a=>{a.filter(a=>a.isIntersecting).forEach(a=>{const b=a.target,{width:c,height:f}=a.intersectionRect;e(b,()=>{const a=performance.now();d(b,c*f,a)})})}),c(h),y.forEach(b=>{a(b,j,z)})}function j(a){const b=a.target;"scroll"===a.type&&("expand-trigger"===b?.className||"contract-trigger"===b?.className)||0===o||250>performance.now()-n||k()}function k(){w?.disconnect(),y.forEach(a=>{b(a,j,z)}),t=!1,w=null}function l(a){x=a,0!==p&&x(p,m,o)}let m,n=0,o=0,p=0;const q=666778e-9;let r,s=!1,t=!0;const u=["IMG","H1","H2","H3","H4","H5","SVG"];let v,w,x;const y=["click","mousedown","keydown","touchstart","pointerdown","scroll"],z={passive:!0,capture:!0};i(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onLargestContentfulPaint=l,self.perfMetrics.startSearchingForLargestContentfulPaint=i.bind(null,!1),self.perfMetrics.stopSearchingForLargestContentfulPaint=k,self.perfMetrics.markIsHydratedForLargestContentfulPaint=()=>{s=!0},self.perfMetrics.registerLCPCandidate=f,self.perfMetrics.inspectLCPTarget=()=>m})(addEventListener,removeEventListener,requestAnimationFrame);
// INP init code.
(function(a){var b=Math.max,c=Math.min;function d(){return null==t?null==performance.interactionCount?0:performance.interactionCount:u}function e(){const a=d()-n;return a}function f(){const a=c(r.length-1,Math.floor(e()/50));return r[a]}function g(){"PerformanceObserver"in window&&PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("event")&&(y(),m=new PerformanceObserver(a=>{Promise.resolve().then(()=>{const b=a.getEntries();i(b)})}),m.observe({type:"event",buffered:!0,durationThreshold:40}),m.observe({type:"first-input",buffered:!0}),a("visibilitychange",j,!0),a("pageshow",k,!0))}function h(a){if(null==a.interactionId)return;const c=r[r.length-1],d=s.get(a.interactionId);if(null!=d||r.length<q||a.duration>c.latency){if(null!=d)d.entries.push(a),d.latency=b(d.latency,a.duration);else{const b={id:a.interactionId,latency:a.duration,entries:[a]};r.push(b),s.set(a.interactionId,b)}r.sort((c,a)=>a.latency-c.latency),r.splice(q).forEach(a=>{s.delete(a.id)})}}function i(a){a.forEach(a=>{a.interactionId&&h(a)});const b=f();b&&b.latency!==o.value&&(o.value=b.latency,o.entries=b.entries,l())}function j(){null==m||"hidden"===document.visibilityState&&(i(m.takeRecords()),0>o.value&&0<e()&&(o.value=0,o.entries=[]),l())}function k(a){a.persisted&&(r=[],s.clear(),n=d(),o.value=-1,o.entries=[])}function l(){p&&p(o.value,o.entries)}let m,n=0;const o={value:-1,entries:[]};let p;const q=10;let r=[];const s=new Map;let t,u=0,v=1/0,w=0;const x=a=>{a.forEach(a=>{a.interactionId&&(v=c(v,a.interactionId),w=b(w,a.interactionId),u=w?(w-v)/7+1:0)})},y=()=>{"interactionCount"in performance||null!=t||PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("event")&&(t=new PerformanceObserver(a=>{Promise.resolve().then(()=>{x(a.getEntries())})}),t.observe({type:"event",buffered:!0,durationThreshold:0}))};g(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onInp=function(a){0<=o.value?a(o.value,o.entries):p=a},self.perfMetrics.clearInp=function(){r=[],s.clear(),n=0,u=0,v=1/0,w=0,o.value=-1,o.entries=[]}})(addEventListener);

In [15]:
type(soup)

bs4.BeautifulSoup

Definir los datos que queremos sacar

In [17]:
lista_titulos=[]
lista_tipo_hab=[]
lista_valoracion=[]
lista_num_valoracion=[]
lista_ciudad=[]
lista_localidad=[]
lista_baño=[]
lista_dormitorios=[]
lista_camas=[]
lista_viajeros=[]
lista_precio_inicial=[]

lista_titulos.append(soup.find("h1",{"elementtiming":"LCP-target"}).text.strip())

lista_tipo_hab.append(soup.find('h2',{'elementtiming':'LCP-target'}).text.split()[0])

lista_valoracion.append(soup.find("div", {"class":"r1lutz1s"}).text.strip())

lista_num_valoracion.append(soup.find("a",{"class":"l1ovpqvx atm_1he2i46_1k8pnbi_10saat9 atm_yxpdqi_1pv6nv4_10saat9 atm_1a0hdzc_w1h1e8_10saat9 atm_ywwsz3_1afjdsa_10saat9 atm_1lnvhrj_zhgkwc_10saat9 atm_8i46q5_63ecz1_10saat9 b1uxatsa atm_c8_1kw7nm4 atm_bx_1kw7nm4 atm_cd_1kw7nm4 atm_ci_1kw7nm4 atm_g3_1kw7nm4 atm_9j_tlke0l_1nos8r_uv4tnr atm_7l_1kw7nm4_pfnrn2 atm_rd_8stvzk_pfnrn2 c1qih7tm atm_1s_glywfm atm_26_1j28jx2 atm_3f_idpfg4 atm_9j_tlke0l atm_gi_idpfg4 atm_l8_idpfg4 atm_vb_1wugsn5 atm_7l_jt7fhx atm_rd_8stvzk atm_5j_1896hn4 atm_cs_9dzvea atm_r3_1kw7nm4 atm_mk_h2mmj6 atm_kd_glywfm atm_9j_13gfvf7_1o5j5ji atm_7l_jt7fhx_v5whe7 atm_rd_8stvzk_v5whe7 atm_7l_177r58q_1nos8r_uv4tnr atm_rd_8stvzk_1nos8r_uv4tnr atm_7l_9vytuy_4fughm_uv4tnr atm_rd_8stvzk_4fughm_uv4tnr atm_rd_8stvzk_xggcrc_uv4tnr atm_7l_1he744i_csw3t1 atm_rd_8stvzk_csw3t1 atm_3f_glywfm_jo46a5 atm_l8_idpfg4_jo46a5 atm_gi_idpfg4_jo46a5 atm_3f_glywfm_1icshfk atm_kd_glywfm_19774hq atm_7l_jt7fhx_1w3cfyq atm_rd_8stvzk_1w3cfyq atm_uc_aaiy6o_1w3cfyq atm_70_1p56tq7_1w3cfyq atm_uc_glywfm_1w3cfyq_1rrf6b5 atm_7l_jt7fhx_pfnrn2_1oszvuo atm_rd_8stvzk_pfnrn2_1oszvuo atm_uc_aaiy6o_pfnrn2_1oszvuo atm_70_1p56tq7_pfnrn2_1oszvuo atm_uc_glywfm_pfnrn2_1o31aam atm_7l_9vytuy_1o5j5ji atm_rd_8stvzk_1o5j5ji atm_rd_8stvzk_1mj13j2 dir dir-ltr"}).text.strip())

lista_localidad.append(soup.find('div',{'class':'_152qbzi'}).text.split()[0].replace(",","").strip())

baños = soup.find("ol", {"class":"lgx66tx"}).text.lower().strip()
if "baño compartido" in baños:
        index= baños.find("baño")
        lista_baño.append(baños[index:])
elif "baño" or "Baño" in baños:
        index= baños.find("baño")
        lista_baño.append(baños[index -2:])
else:
        lista_baño.append(baño= "Sin baños")

dormitorios = soup.find("ol", {"class":"lgx66tx"}).text.lower().strip()
if "dormirtorio" in dormitorios:
        index= dormitorios.find("dormitorio")
        lista_dormitorios.append(dormitorios[index -2: index + 10])
elif "dormitorios" in dormitorios:
        index= dormitorios.find("dormitorios")
        lista_dormitorios.append(dormitorios[index -2:index + 11])
else:
        lista_dormitorios.append("1 dormitorio")

camas = soup.find("ol", {"class":"lgx66tx"}).text.lower().strip()
if "cama" in camas:
        index= camas.find("cama")
        lista_camas.append(camas[index -2: index + 5])
elif "camas" in camas:
        index= camas.find("camas")
        lista_camas.append(camas[index -2: index + 6])
else:
        lista_camas.append("No especificado")

viajeros = soup.find("ol", {"class":"lgx66tx"}).text.lower().strip()
if "viajero" in viajeros:
        index= viajeros.find("viajero")
        lista_viajeros.append(viajeros[index -2: index + 8].replace("\xa0"," "))
elif "viajeros" in viajeros:
        index= viajeros.find("viajeros")
        lista_viajeros.append(viajeros[index -2: index + 9].replace("\xa0"," "))
else:
        lista_viajeros.append("No especificado")

lista_precio_inicial.append(int(soup.find('span',{'class':'_1y74zjx'}).text.replace("\xa0", "").replace("€", "").strip()))

lista_ciudad.append(soup.find('h2',{'elementtiming':'LCP-target'}).text.split()[-2].replace(',',''))

In [18]:
print(lista_titulos)
print(lista_tipo_hab)
print(lista_valoracion)
print(lista_num_valoracion)
print(lista_ciudad)
print(lista_localidad)
print(lista_baño)
print(lista_dormitorios)
print(lista_camas)
print(lista_viajeros)
print(lista_precio_inicial)

['Habitación en palma']
['Habitación']
['Nuevo']
['1 evaluación']
['Palma']
['Palma']
['baño compartido']
['1 dormitorio']
['No especificado']
['No especificado']
[46]

In [19]:
#Mostrar todas las caracteristicas
button_more = browser.find_element(by=By.XPATH, value="/html/body/div[5]/div/div/div[1]/div/div[2]/div/div/div/div[1]/main/div/div[1]/div[3]/div/div[1]/div/div[7]/div/div[2]/section/div[3]/button")

button_more.click()
time.sleep(5)
print("Ver todas las caracteristicas")

Ver todas las caracteristicas

In [20]:
html2 = browser.page_source
html2

'<html lang="es" dir="ltr" data-is-hyperloop="true" data-hyperloop-version="2" class="scrollbar-gutter g5l85gq dir native v1oc6b3k vgnbcm1 v1agkal2 vqw89vp vlugpmm" style="--vh: 6.5px; --vw: 9.96px; --vw-unitless: 996; min-height: calc(var(--vh, 1vh) * 100); scrollbar-gutter: auto;"><head><meta charset="utf-8"><meta name="locale" content="es"><meta name="google" content="notranslate"><meta id="csrf-param-meta-tag" name="csrf-param" content="authenticity_token"><meta id="csrf-token-meta-tag" name="csrf-token" content="null"><meta id="english-canonical-url" content=""><meta name="twitter:widgets:csp" content="on"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="application-name" content="Airbnb"><meta name="apple-mobile-web-app-title" content="Airbnb"><meta name="theme-color" content="#ffffff"><meta name="msapplication-navbutton-color" content="#ffffff"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="msapplication-starturl" content="/?utm_source=homescreen"><link href="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/apps/core-guest-spa/client.3a2af6a5bd.css" rel="stylesheet" type="text/css" media="all" crossorigin="anonymous"><script src="https://connect.facebook.net/es_ES/sdk.js?hash=de39385d1413973ab7f943bddcad325e" async="" crossorigin="anonymous"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-788919195&amp;l=dataLayer&amp;cx=c"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/destination?id=DC-4620401&amp;l=dataLayer&amp;cx=c"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-1023009977&amp;l=dataLayer&amp;cx=c"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-2P6Q8PGG16&amp;l=dataLayer&amp;cx=c"></script><script defer="" src="https://www.googletagmanager.com/gtm.js?id=GTM-46MK"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/metroRequire.ae703c8f7e.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/shims_post_modules.3a508a05ae.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/airmetro/src/browser/asyncRequire.850c368e1e.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/coreV2.d6f9f63d25.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/routeHandler.eb80466977.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/4199.5e3bb90aec.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/6c27.fa954d98a5.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/8bc1.8f6a9e34a1.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/10f8.9117338e7d.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/node_modules/moment/locale/es.2078639028.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/apps/core-guest-spa/initializer.c6c1050f75.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/guest-header/query/HeaderQuery.prepare.d7f2b63b5c.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/08bb.14cb15ead3.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/c716.39066a3328.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/niobe/minimalist/index.e2c6bf6af5.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/5ab1.8a29ff2ccd.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/ab3c.bffef7a3ec.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/8bdd.c7d7b43b08.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/215b.45a018a6e8.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/1a9c.d2142d9ebd.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/3ccd.c8194e5b79.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/0d90.ade6c80b29.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/28bf.31bec2cd3d.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/gp-stays-pdp-route/routes/PdpPlatformRoute.731fbc50ad.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/gp-stays-pdp-route/routes/PdpPlatformRouteSkeleton.prepare.8a14af814b.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/f4c9f.a8028461f8.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/0f40.653b543916.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/a2ec.121a9da08c.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/4857.55b4640d65.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/e008.b6070a7705.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/e3a3.8014d0c86b.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/1cc0.9a9004ba18.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/2b64.48dfb6f865.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/19be.ec5149f10f.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/core-guest-loop/apps/core-guest-spa/client.6cef39f3f1.js" defer="" crossorigin="anonymous"></script><script>(function() {\n  // pg_pixel is no-op now.\n})()</script><script>(function(){function a(c){if(window._errorReportingInitialized)return void window.removeEventListener("error",a);const{error:d}=c;if(!d)return;const e=c.message||d.message,f=/Requiring unknown module/.test(e)?1/100:1/10;if(Math.random()>f)return;const{locale:g,tracking_context:h}=window[Symbol.for("__ global cache key __")]?.["string | airbnb-bootstrap-data"]?.["_bootstrap-layout-init"]??{},i=g||navigator.language,j=location.pathname,k="undefined"==typeof window?{sampleRate:f+""}:{tags:{loggingSource:"browser",sampleRate:f+""}};fetch("https://notify.bugsnag.com/",{headers:{"Bugsnag-Payload-Version":"5"},body:JSON.stringify({apiKey:"e393bc25e52fe915ffb56c14ddf2ff1b",payloadVersion:b,notifier:{name:"Bugsnag JavaScript",version:"0.0.5-AirbnbUnhandledBufferedErrorCustomFetch",url:""},events:[{exceptions:[{errorClass:d.name,message:e,stacktrace:[{file:c.filename,lineNumber:c.lineno,columnNumber:c.colno}],type:"browserjs"}],request:{url:location.href},context:j,groupingHash:d.name.concat("-",e,"-",j),unhandled:!0,app:{releaseStage:h?.environment},device:{time:new Date,userAgent:navigator.userAgent},metaData:{infra:{app_name:h?.app,is_buffered_error:!0,loop_name:h?.controller,locale:i,service_worker_url:navigator.serviceWorker?.controller?.scriptURL},...k}}]}),method:"POST"})}const b="5";"undefined"!=typeof window&&window.addEventListener("error",a)})();</script><script>\n// FID init code.\n(function(a,b){function c(a){l.push(a),f()}function d(a,b){i||(i=b,j=a,k=new Date,f())}function e(){i&&(i=null,j=null,k=null)}function f(){0<=j&&j<k-n&&(l.forEach(a=>{a(j,i)}),l=[])}function g(c,e){function f(){d(c,e),h()}function g(){h()}function h(){b(o,f,m),b(p,g,m)}a(o,f,m),a(p,g,m)}function h(a){if(a.cancelable){const b=1e12<a.timeStamp,c=b?new Date:performance.now(),e=c-a.timeStamp;"pointerdown"===a.type?g(e,a):d(e,a)}}let i,j,k,l=[];const m={passive:!0,capture:!0},n=new Date,o="pointerup",p="pointercancel";(function(a){["click","mousedown","keydown","touchstart","pointerdown"].forEach(b=>{a(b,h,m)})})(a),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=c,self.perfMetrics.clearFirstInputDelay=e})(addEventListener,removeEventListener);\n// TTFMP Polyfill code.\n(function(a){function b(){const c=document.getElementById(i);h=0,c?g===c?e=a(b):"IMG"!==c.tagName||c.complete?a(function(){const a=performance.now();g=c,f?f(a):h=a,performance.measure&&performance.measure("TTFMP")}):e=a(b):e=a(b)}function c(a){h?a(h):f=a}function d(){cancelAnimationFrame(e)}let e,f,g,h;const i="FMP-target";e=a(b),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstMeaningfulPaint=c,self.perfMetrics.startSearchingForFirstMeaningfulPaint=function(){g=document.getElementById(i),b()},self.perfMetrics.stopSearchingForFirstMeaningfulPaint=d})(requestAnimationFrame);\n// LCP Polyfill code\n(function(a,b,c){function d(a,b,c){(b>o*(1+q)||!document.body.contains(m))&&(o=b,p=c,m=a,x?.(p,m,o))}function e(a,b){if("IMG"!==a.tagName)b();else{const d=()=>c(b);a.complete?d():a.addEventListener("load",d,{once:!0})}}function f(a){w?.observe(a)}function g(a){return u.includes(a.tagName)||a.hasAttribute("data-lcp-candidate")}function h(){if(t)if(s)v||(v={IMG:document.getElementsByTagName("img"),H1:document.getElementsByTagName("h1"),H2:document.getElementsByTagName("h2"),H3:document.getElementsByTagName("h3"),H4:document.getElementsByTagName("h4"),H5:document.getElementsByTagName("h5"),SVG:document.getElementsByTagName("svg")}),u.forEach(a=>{Array.from(v[a]).forEach(a=>{f(a)})}),setTimeout(h,50);else{!r&&document.body&&(r=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,a=>g(a)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT));for(let a;a=r?.nextNode();)f(a);c(h)}}function i(){n=performance.now(),o=0,p=0,w=new IntersectionObserver(a=>{a.filter(a=>a.isIntersecting).forEach(a=>{const b=a.target,{width:c,height:f}=a.intersectionRect;e(b,()=>{const a=performance.now();d(b,c*f,a)})})}),c(h),y.forEach(b=>{a(b,j,z)})}function j(a){const b=a.target;"scroll"===a.type&&("expand-trigger"===b?.className||"contract-trigger"===b?.className)||0===o||250>performance.now()-n||k()}function k(){w?.disconnect(),y.forEach(a=>{b(a,j,z)}),t=!1,w=null}function l(a){x=a,0!==p&&x(p,m,o)}let m,n=0,o=0,p=0;const q=666778e-9;let r,s=!1,t=!0;const u=["IMG","H1","H2","H3","H4","H5","SVG"];let v,w,x;const y=["click","mousedown","keydown","touchstart","pointerdown","scroll"],z={passive:!0,capture:!0};i(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onLargestContentfulPaint=l,self.perfMetrics.startSearchingForLargestContentfulPaint=i.bind(null,!1),self.perfMetrics.stopSearchingForLargestContentfulPaint=k,self.perfMetrics.markIsHydratedForLargestContentfulPaint=()=>{s=!0},self.perfMetrics.registerLCPCandidate=f,self.perfMetrics.inspectLCPTarget=()=>m})(addEventListener,removeEventListener,requestAnimationFrame);\n// INP init code.\n(function(a){var b=Math.max,c=Math.min;function d(){return null==t?null==performance.interactionCount?0:performance.interactionCount:u}function e(){const a=d()-n;return a}function f(){const a=c(r.length-1,Math.floor(e()/50));return r[a]}function g(){"PerformanceObserver"in window&&PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("event")&&(y(),m=new PerformanceObserver(a=>{Promise.resolve().then(()=>{const b=a.getEntries();i(b)})}),m.observe({type:"event",buffered:!0,durationThreshold:40}),m.observe({type:"first-input",buffered:!0}),a("visibilitychange",j,!0),a("pageshow",k,!0))}function h(a){if(null==a.interactionId)return;const c=r[r.length-1],d=s.get(a.interactionId);if(null!=d||r.length<q||a.duration>c.latency){if(null!=d)d.entries.push(a),d.latency=b(d.latency,a.duration);else{const b={id:a.interactionId,latency:a.duration,entries:[a]};r.push(b),s.set(a.interactionId,b)}r.sort((c,a)=>a.latency-c.latency),r.splice(q).forEach(a=>{s.delete(a.id)})}}function i(a){a.forEach(a=>{a.interactionId&&h(a)});const b=f();b&&b.latency!==o.value&&(o.value=b.latency,o.entries=b.entries,l())}function j(){null==m||"hidden"===document.visibilityState&&(i(m.takeRecords()),0>o.value&&0<e()&&(o.value=0,o.entries=[]),l())}function k(a){a.persisted&&(r=[],s.clear(),n=d(),o.value=-1,o.entries=[])}function l(){p&&p(o.value,o.entries)}let m,n=0;const o={value:-1,entries:[]};let p;const q=10;let r=[];const s=new Map;let t,u=0,v=1/0,w=0;const x=a=>{a.forEach(a=>{a.interactionId&&(v=c(v,a.interactionId),w=b(w,a.interactionId),u=w?(w-v)/7+1:0)})},y=()=>{"interactionCount"in performance||null!=t||PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("event")&&(t=new PerformanceObserver(a=>{Promise.resolve().then(()=>{x(a.getEntries())})}),t.observe({type:"event",buffered:!0,durationThreshold:0}))};g(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onInp=function(a){0<=o.value?a(o.value,o.entries):p=a},self.perfMetrics.clearInp=function(){r=[],s.clear(),n=0,u=0,v=1/0,w=0,o.value=-1,o.entries=[]}})(addEventListener);\n</script><script>((a,b,c,d)=>{if(d.supports("(font: -apple-system-body) and (-webkit-touch-callout: default)")){const d=a.createElement("div");d.setAttribute("style","font: -apple-system-body"),b.appendChild(d);const e=c(d);"17px"===e.fontSize&&b.style.setProperty("--root-font-size","16px"),b.removeChild(d)}})(document,document.documentElement,getComputedStyle,CSS);</script><link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="Airbnb"><link rel="apple-touch-icon" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-76x76-3b313d93b1b5823293524b9764352ac9.png"><link rel="apple-touch-icon" sizes="76x76" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-76x76-3b313d93b1b5823293524b9764352ac9.png"><link rel="apple-touch-icon" sizes="120x120" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-120x120-52b1adb4fe3a8f825fc4b143de12ea4b.png"><link rel="apple-touch-icon" sizes="152x152" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-152x152-7b7c6444b63d8b6ebad9dae7169e5ed6.png"><link rel="apple-touch-icon" sizes="180x180" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-180x180-bcbe0e3960cd084eb8eaf1353cf3c730.png"><link rel="icon" sizes="192x192" href="https://a0.muscache.com/airbnb/static/icons/android-icon-192x192-c0465f9f0380893768972a31a614b670.png"><link rel="shortcut icon" sizes="76x76" type="image/x-icon" href="https://a0.muscache.com/airbnb/static/logotype_favicon-21cc8e6c6a2cca43f061d2dcabdf6e58.ico"><link rel="mask-icon" href="https://a0.muscache.com/airbnb/static/icons/airbnb-0611901eac33ccfa5e93d793a2e21f09.svg" color="#FF5A5F"><link href="https://a0.muscache.com/airbnb/static/packages/dls/dls-lite_cereal-47d27fa833e062fe3413637eb751001f.css" rel="stylesheet" type="text/css" media="all" crossorigin="anonymous"><meta content="width=device-width, initial-scale=1, viewport-fit=cover" name="viewport"><style data-aphrodite="true" id="aphrodite" type="text/css">._9r8p20{color:#222222 !important;font-family:Circular,-apple-system,BlinkMacSystemFont,Roboto,Helvetica Neue,sans-serif !important;font-weight:400 !important;font-size:1rem !important;line-height:1.25rem !important;--gp-section-compact-padding:32px !important;--gp-section-compact-padding-condensed:16px !important;--gp-section-standard-padding:48px !important;--gp-section-standard-padding-condensed:24px !important;}._1k81gub{position:relative !important;}@supports (height: 1dvh){._1k81gub{min-height:100dvh !important;}}@supports not (height: 1dvh){._1k81gub{min-height:-webkit-calc(100 * var(--vh) - env(safe-area-inset-bottom, 0px)) !important;min-height:-moz-calc(100 * var(--vh) - env(safe-area-inset-bottom, 0px)) !important;min-height:calc(100 * var(--vh) - env(safe-area-inset-bottom, 0px)) !important;}}._siy8gh{display:none !important;}@media (min-width: 744px){._siy8gh{display:block !important;}}._vuzcgs{-webkit-box-pack:end !important;-ms-flex-pack:end !important;-webkit-box-align:center !important;-ms-flex-align:center !important;position:relative !important;display:-webkit-box !important;display:-moz-box !important;display:-ms-flexbox !important;display:-webkit-flex !important;display:flex !important;-webkit-align-items:center !important;align-items:center !important;-webkit-justify-content:flex-end !important;justify-content:flex-end !important;height:80px !important;}._176ugpa{-webkit-box-pack:end !important;-ms-flex-pack:end !important;display:-webkit-box !important;display:-moz-box !important;display:-ms-flexbox !important;display:-webkit-flex !important;display:flex !important;-webkit-flex:auto !important;-ms-flex:1 1 auto !important;flex:auto !important;-webkit-justify-content:flex-end !important;justify-content:flex-end !important;margin-right:8px !important;}._pvfq6t{position:relative !important;display:inline-block !important;vertical-align:middle !important;margin-top:auto !important;margin-bottom:auto !important;}._z5mecy{-webkit-box-align:center !important;-ms-flex-align:center !important;-webkit-align-items:center !important;align-items:center !important;display:-webkit-box !important;display:-moz-box !important;display:-ms-flexbox !important;display:-webkit-flex !important;display:flex !important;height:18px !important;position:relative !important;z-index:1 !important;}._167wsvl{display:inline !important;position:relative !important;}._88xxct{display:none !important;}@media print{._88xxct{display:block !important;}}@media (min-width: 744px){._88xxct{display:block !important;}}._1a6d9c4{-webkit-box-lines:multiple !important;-webkit-box-pack:start !important;-ms-flex-pack:start !important;-webkit-box-align:stretch !important;-ms-flex-align:stretch !important;display:-webkit-box !important;display:-moz-box !important;display:-ms-flexbox !important;display:-webkit-flex !important;display:flex !important;-webkit-align-items:stretch !important;align-items:stretch !important;-webkit-justify-content:flex-start !important;justify-content:flex-start !important;-webkit-flex-wrap:wrap !important;-ms-flex-wrap:wrap !important;flex-wrap:wrap !important;width:100% !important;padding-left:var(--gp-padding-xsmallAndAbove, 24px) !important;padding-right:var(--gp-padding-xsmallAndAbove, 24px) !important;margin-left:0px !important;margin-right:0px !important;}@media (min-width: 375px){._1a6d9c4{padding-left:var(--gp-padding-smallAndAbove, 24px) !important;padding-right:var(--gp-padding-smallAndAbove, 24px) !important;}}@media (min-width: 744px){._1a6d9c4{padding-left:var(--gp-padding-mediumAndAbove, 40px) !important;padding-right:var(--gp-padding-mediumAndAbove, 40px) !important;}}@media (min-width: 950px){._1a6d9c4{padding-left:var(--gp-padding-mediumPlusAnd

In [21]:
soup = bs(html2, 'lxml')
soup

<html class="scrollbar-gutter g5l85gq dir native v1oc6b3k vgnbcm1 v1agkal2 vqw89vp vlugpmm" data-hyperloop-version="2" data-is-hyperloop="true" dir="ltr" lang="es" style="--vh: 6.5px; --vw: 9.96px; --vw-unitless: 996; min-height: calc(var(--vh, 1vh) * 100); scrollbar-gutter: auto;"><head><meta charset="utf-8"/><meta content="es" name="locale"/><meta content="notranslate" name="google"/><meta content="authenticity_token" id="csrf-param-meta-tag" name="csrf-param"/><meta content="null" id="csrf-token-meta-tag" name="csrf-token"/><meta content="" id="english-canonical-url"/><meta content="on" name="twitter:widgets:csp"/><meta content="yes" name="mobile-web-app-capable"/><meta content="yes" name="apple-mobile-web-app-capable"/><meta content="Airbnb" name="application-name"/><meta content="Airbnb" name="apple-mobile-web-app-title"/><meta content="#ffffff" name="theme-color"/><meta content="#ffffff" name="msapplication-navbutton-color"/><meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"/><meta content="/?utm_source=homescreen" name="msapplication-starturl"/><link crossorigin="anonymous" href="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/apps/core-guest-spa/client.3a2af6a5bd.css" media="all" rel="stylesheet" type="text/css"/><script async="" crossorigin="anonymous" src="https://connect.facebook.net/es_ES/sdk.js?hash=de39385d1413973ab7f943bddcad325e"></script><script async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-788919195&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/destination?id=DC-4620401&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-1023009977&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-2P6Q8PGG16&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script defer="" src="https://www.googletagmanager.com/gtm.js?id=GTM-46MK"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/metroRequire.ae703c8f7e.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/shims_post_modules.3a508a05ae.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/airmetro/src/browser/asyncRequire.850c368e1e.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/coreV2.d6f9f63d25.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/routeHandler.eb80466977.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/4199.5e3bb90aec.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/6c27.fa954d98a5.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/8bc1.8f6a9e34a1.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/10f8.9117338e7d.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/node_modules/moment/locale/es.2078639028.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/apps/core-guest-spa/initializer.c6c1050f75.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/guest-header/query/HeaderQuery.prepare.d7f2b63b5c.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/08bb.14cb15ead3.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/c716.39066a3328.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/niobe/minimalist/index.e2c6bf6af5.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/5ab1.8a29ff2ccd.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/ab3c.bffef7a3ec.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/8bdd.c7d7b43b08.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/215b.45a018a6e8.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/1a9c.d2142d9ebd.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/3ccd.c8194e5b79.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/0d90.ade6c80b29.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/28bf.31bec2cd3d.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/gp-stays-pdp-route/routes/PdpPlatformRoute.731fbc50ad.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/gp-stays-pdp-route/routes/PdpPlatformRouteSkeleton.prepare.8a14af814b.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/f4c9f.a8028461f8.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/0f40.653b543916.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/a2ec.121a9da08c.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/4857.55b4640d65.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/e008.b6070a7705.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/e3a3.8014d0c86b.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/1cc0.9a9004ba18.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/2b64.48dfb6f865.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/19be.ec5149f10f.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/core-guest-loop/apps/core-guest-spa/client.6cef39f3f1.js"></script><script>(function() {
  // pg_pixel is no-op now.
})()</script><script>(function(){function a(c){if(window._errorReportingInitialized)return void window.removeEventListener("error",a);const{error:d}=c;if(!d)return;const e=c.message||d.message,f=/Requiring unknown module/.test(e)?1/100:1/10;if(Math.random()>f)return;const{locale:g,tracking_context:h}=window[Symbol.for("__ global cache key __")]?.["string | airbnb-bootstrap-data"]?.["_bootstrap-layout-init"]??{},i=g||navigator.language,j=location.pathname,k="undefined"==typeof window?{sampleRate:f+""}:{tags:{loggingSource:"browser",sampleRate:f+""}};fetch("https://notify.bugsnag.com/",{headers:{"Bugsnag-Payload-Version":"5"},body:JSON.stringify({apiKey:"e393bc25e52fe915ffb56c14ddf2ff1b",payloadVersion:b,notifier:{name:"Bugsnag JavaScript",version:"0.0.5-AirbnbUnhandledBufferedErrorCustomFetch",url:""},events:[{exceptions:[{errorClass:d.name,message:e,stacktrace:[{file:c.filename,lineNumber:c.lineno,columnNumber:c.colno}],type:"browserjs"}],request:{url:location.href},context:j,groupingHash:d.name.concat("-",e,"-",j),unhandled:!0,app:{releaseStage:h?.environment},device:{time:new Date,userAgent:navigator.userAgent},metaData:{infra:{app_name:h?.app,is_buffered_error:!0,loop_name:h?.controller,locale:i,service_worker_url:navigator.serviceWorker?.controller?.scriptURL},...k}}]}),method:"POST"})}const b="5";"undefined"!=typeof window&&window.addEventListener("error",a)})();</script><script>
// FID init code.
(function(a,b){function c(a){l.push(a),f()}function d(a,b){i||(i=b,j=a,k=new Date,f())}function e(){i&&(i=null,j=null,k=null)}function f(){0<=j&&j<k-n&&(l.forEach(a=>{a(j,i)}),l=[])}function g(c,e){function f(){d(c,e),h()}function g(){h()}function h(){b(o,f,m),b(p,g,m)}a(o,f,m),a(p,g,m)}function h(a){if(a.cancelable){const b=1e12<a.timeStamp,c=b?new Date:performance.now(),e=c-a.timeStamp;"pointerdown"===a.type?g(e,a):d(e,a)}}let i,j,k,l=[];const m={passive:!0,capture:!0},n=new Date,o="pointerup",p="pointercancel";(function(a){["click","mousedown","keydown","touchstart","pointerdown"].forEach(b=>{a(b,h,m)})})(a),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=c,self.perfMetrics.clearFirstInputDelay=e})(addEventListener,removeEventListener);
// TTFMP Polyfill code.
(function(a){function b(){const c=document.getElementById(i);h=0,c?g===c?e=a(b):"IMG"!==c.tagName||c.complete?a(function(){const a=performance.now();g=c,f?f(a):h=a,performance.measure&&performance.measure("TTFMP")}):e=a(b):e=a(b)}function c(a){h?a(h):f=a}function d(){cancelAnimationFrame(e)}let e,f,g,h;const i="FMP-target";e=a(b),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstMeaningfulPaint=c,self.perfMetrics.startSearchingForFirstMeaningfulPaint=function(){g=document.getElementById(i),b()},self.perfMetrics.stopSearchingForFirstMeaningfulPaint=d})(requestAnimationFrame);
// LCP Polyfill code
(function(a,b,c){function d(a,b,c){(b>o*(1+q)||!document.body.contains(m))&&(o=b,p=c,m=a,x?.(p,m,o))}function e(a,b){if("IMG"!==a.tagName)b();else{const d=()=>c(b);a.complete?d():a.addEventListener("load",d,{once:!0})}}function f(a){w?.observe(a)}function g(a){return u.includes(a.tagName)||a.hasAttribute("data-lcp-candidate")}function h(){if(t)if(s)v||(v={IMG:document.getElementsByTagName("img"),H1:document.getElementsByTagName("h1"),H2:document.getElementsByTagName("h2"),H3:document.getElementsByTagName("h3"),H4:document.getElementsByTagName("h4"),H5:document.getElementsByTagName("h5"),SVG:document.getElementsByTagName("svg")}),u.forEach(a=>{Array.from(v[a]).forEach(a=>{f(a)})}),setTimeout(h,50);else{!r&&document.body&&(r=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,a=>g(a)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT));for(let a;a=r?.nextNode();)f(a);c(h)}}function i(){n=performance.now(),o=0,p=0,w=new IntersectionObserver(a=>{a.filter(a=>a.isIntersecting).forEach(a=>{const b=a.target,{width:c,height:f}=a.intersectionRect;e(b,()=>{const a=performance.now();d(b,c*f,a)})})}),c(h),y.forEach(b=>{a(b,j,z)})}function j(a){const b=a.target;"scroll"===a.type&&("expand-trigger"===b?.className||"contract-trigger"===b?.className)||0===o||250>performance.now()-n||k()}function k(){w?.disconnect(),y.forEach(a=>{b(a,j,z)}),t=!1,w=null}function l(a){x=a,0!==p&&x(p,m,o)}let m,n=0,o=0,p=0;const q=666778e-9;let r,s=!1,t=!0;const u=["IMG","H1","H2","H3","H4","H5","SVG"];let v,w,x;const y=["click","mousedown","keydown","touchstart","pointerdown","scroll"],z={passive:!0,capture:!0};i(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onLargestContentfulPaint=l,self.perfMetrics.startSearchingForLargestContentfulPaint=i.bind(null,!1),self.perfMetrics.stopSearchingForLargestContentfulPaint=k,self.perfMetrics.markIsHydratedForLargestContentfulPaint=()=>{s=!0},self.perfMetrics.registerLCPCandidate=f,self.perfMetrics.inspectLCPTarget=()=>m})(addEventListener,removeEventListener,requestAnimationFrame);
// INP init code.
(function(a){var b=Math.max,c=Math.min;function d(){return null==t?null==performance.interactionCount?0:performance.interactionCount:u}function e(){const a=d()-n;return a}function f(){const a=c(r.length-1,Math.floor(e()/50));return r[a]}function g(){"PerformanceObserver"in window&&PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("event")&&(y(),m=new PerformanceObserver(a=>{Promise.resolve().then(()=>{const b=a.getEntries();i(b)})}),m.observe({type:"event",buffered:!0,durationThreshold:40}),m.observe({type:"first-input",buffered:!0}),a("visibilitychange",j,!0),a("pageshow",k,!0))}function h(a){if(null==a.interactionId)return;const c=r[r.length-1],d=s.get(a.interactionId);if(null!=d||r.length<q||a.duration>c.latency){if(null!=d)d.entries.push(a),d.latency=b(d.latency,a.duration);else{const b={id:a.interactionId,latency:a.duration,entries:[a]};r.push(b),s.set(a.interactionId,b)}r.sort((c,a)=>a.latency-c.latency),r.splice(q).forEach(a=>{s.delete(a.id)})}}function i(a){a.forEach(a=>{a.interactionId&&h(a)});const b=f();b&&b.latency!==o.value&&(o.value=b.latency,o.entries=b.entries,l())}function j(){null==m||"hidden"===document.visibilityState&&(i(m.takeRecords()),0>o.value&&0<e()&&(o.value=0,o.entries=[]),l())}function k(a){a.persisted&&(r=[],s.clear(),n=d(),o.value=-1,o.entries=[])}function l(){p&&p(o.value,o.entries)}let m,n=0;const o={value:-1,entries:[]};let p;const q=10;let r=[];const s=new Map;let t,u=0,v=1/0,w=0;const x=a=>{a.forEach(a=>{a.interactionId&&(v=c(v,a.interactionId),w=b(w,a.interactionId),u=w?(w-v)/7+1:0)})},y=()=>{"interactionCount"in performance||null!=t||PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("event")&&(t=new PerformanceObserver(a=>{Promise.resolve().then(()=>{x(a.getEntries())})}),t.observe({type:"event",buffered:!0,durationThreshold:0}))};g(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onInp=function(a){0<=o.value?a(o.value,o.entries):p=a},self.perfMetrics.clearInp=function(){r=[],s.clear(),n=0,u=0,v=1/0,w=0,o.value=-1,o.entries=[]}})(addEventListener);

In [22]:
caract = soup.find('div',{'class':'_17itzz4'})
caract

<div class="_17itzz4" style="padding: 40px 24px 24px;"><div class="_1w8roezx" tabindex="0"><div class="d99wcva atm_1htbn05_1ijyn0d atm_m4qiaa_dezgoh atm_nmhd1s_9dzvea atm_n738wd_11rlvjh atm_ff14j6_1xap3gc atm_1strswt_a4yf11 atm_vvc489_xzcxe3 atm_bmoam2_1ijyn0d dir dir-ltr"><div class="_3hmsj"><section><div class="_nvboop"><h2 class="hpipapi atm_7l_1kw7nm4 atm_c8_1x4eueo atm_cs_1kw7nm4 atm_g3_1kw7nm4 atm_gi_idpfg4 atm_l8_idpfg4 atm_kd_idpfg4_pfnrn2 dir dir-ltr" elementtiming="LCP-target" tabindex="-1">¿Qué hay en este alojamiento?</h2></div><div><div class="_11jhslp"><div class="_87jbxlz"><h3 class="hpipapi atm_7l_1kw7nm4 atm_c8_1x4eueo atm_cs_1kw7nm4 atm_g3_1kw7nm4 atm_gi_idpfg4 atm_l8_idpfg4 atm_kd_idpfg4_pfnrn2 dir dir-ltr" elementtiming="LCP-target" tabindex="-1">Dormitorio y lavandería</h3></div><ul class="_2f5j8p" role="list"><li><div class="rten07p atm_lo_1tcgj5g atm_le_1tcgj5g atm_5j_t94yts dir dir-ltr" id="pdp_v3_bedroom_laundry_33_1114500207597778842-0"><div class="f16mr5nx atm_9s_1txwivl dir dir-ltr"><div class="lhg7v4y atm_h0_exct8b dir dir-ltr"><div class="i12mny15 atm_j6_1jbyh58 atm_9s_1txwivl atm_h_1h6ojuz dir dir-ltr"><svg aria-hidden="true" focusable="false" role="presentation" style="display: block; height: 24px; width: 24px; fill: currentcolor;" viewbox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="M26.29 2a3 3 0 0 1 2.96 2.58c.5 3.56.75 7.37.75 11.42s-.25 7.86-.75 11.42a3 3 0 0 1-2.79 2.57l-.17.01H5.7a3 3 0 0 1-2.96-2.58C2.25 23.86 2 20.05 2 16s.25-7.86.75-11.42a3 3 0 0 1 2.79-2.57L5.7 2zm0 2H5.72a1 1 0 0 0-1 .86A80.6 80.6 0 0 0 4 16c0 3.96.24 7.67.73 11.14a1 1 0 0 0 .87.85l.11.01h20.57a1 1 0 0 0 1-.86c.48-3.47.72-7.18.72-11.14 0-3.96-.24-7.67-.73-11.14A1 1 0 0 0 26.3 4zM16 7a9 9 0 1 1 0 18 9 9 0 0 1 0-18zm-5.84 7.5c-.34 0-.68.02-1.02.07a7 7 0 0 0 13.1 4.58 9.09 9.09 0 0 1-6.9-2.37l-.23-.23a6.97 6.97 0 0 0-4.95-2.05zM16 9a7 7 0 0 0-6.07 3.5h.23c2.26 0 4.44.84 6.12 2.4l.24.24a6.98 6.98 0 0 0 6.4 1.9A7 7 0 0 0 16 9zM7 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"></path></svg></div></div><div class="m1ec1bsa atm_9s_1txwivl atm_ar_1bp4okc atm_fc_1h6ojuz atm_am_ggq5uc atm_vy_1osqo2v dir dir-ltr"><div class="twad414 atm_7l_jt7fhx atm_9j_1kw7nm4 atm_bx_48h72j atm_c8_2x1prs atm_g3_1jbyh58 atm_fr_11a07z3 dir dir-ltr" id="pdp_v3_bedroom_laundry_33_1114500207597778842-0-row-title">Lavadora</div></div></div></div><div class="_1wadwfl"></div></li></ul></div><div class="_11jhslp"><div class="_87jbxlz"><h3 class="hpipapi atm_7l_1kw7nm4 atm_c8_1x4eueo atm_cs_1kw7nm4 atm_g3_1kw7nm4 atm_gi_idpfg4 atm_l8_idpfg4 atm_kd_idpfg4_pfnrn2 dir dir-ltr" elementtiming="LCP-target" tabindex="-1">Entretenimiento</h3></div><ul class="_2f5j8p" role="list"><li><div class="rten07p atm_lo_1tcgj5g atm_le_1tcgj5g atm_5j_t94yts dir dir-ltr" id="pdp_v3_entertainment_1_1114500207597778842-0"><div class="f16mr5nx atm_9s_1txwivl dir dir-ltr"><div class="lhg7v4y atm_h0_exct8b dir dir-ltr"><div class="i12mny15 atm_j6_1jbyh58 atm_9s_1txwivl atm_h_1h6ojuz dir dir-ltr"><svg aria-hidden="true" focusable="false" role="presentation" style="display: block; height: 24px; width: 24px; fill: currentcolor;" viewbox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="M9 29v-2h2v-2H6a5 5 0 0 1-5-4.78V8a5 5 0 0 1 4.78-5H26a5 5 0 0 1 5 4.78V20a5 5 0 0 1-4.78 5H21v2h2v2zm10-4h-6v2h6zm7-20H6a3 3 0 0 0-3 2.82V20a3 3 0 0 0 2.82 3H26a3 3 0 0 0 3-2.82V8a3 3 0 0 0-2.82-3z"></path></svg></div></div><div class="m1ec1bsa atm_9s_1txwivl atm_ar_1bp4okc atm_fc_1h6ojuz atm_am_ggq5uc atm_vy_1osqo2v dir dir-ltr"><div class="twad414 atm_7l_jt7fhx atm_9j_1kw7nm4 atm_bx_48h72j atm_c8_2x1prs atm_g3_1jbyh58 atm_fr_11a07z3 dir dir-ltr" id="pdp_v3_entertainment_1_1114500207597778842-0-row-title">TV</div></div></div></div><div class="_1wadwfl"></div></li></ul></div><div class="_11jhslp"><div class="_87jbxlz"><h3 class="hpipapi atm_7l_1kw7nm4 atm_c8_1x4eueo atm_cs_1kw7nm4 atm_g3_1kw7nm4 atm_gi_idpfg4 atm_l8_idpfg4 atm_kd_idpfg4_pfnrn2 dir dir-ltr" elementtiming="LCP-target" tabindex="-1">Privacidad y seguridad</h3></div><ul class="_2f5j8p" role="list"><li><div class="rten07p atm_lo_1tcgj5g atm_le_1tcgj5g atm_5j_t94yts dir dir-ltr" id="lock_on_all_bedroom_doors_9998_1114500207597778842"><div class="f16mr5nx atm_9s_1txwivl dir dir-ltr"><div class="lhg7v4y atm_h0_exct8b dir dir-ltr"><div class="i12mny15 atm_j6_1jbyh58 atm_9s_1txwivl atm_h_1h6ojuz dir dir-ltr"><svg aria-hidden="true" focusable="false" role="presentation" style="display: block; height: 24px; width: 24px; fill: currentcolor;" viewbox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="M25 1a2 2 0 0 1 2 1.85V29h2v2H3v-2h2V3a2 2 0 0 1 1.85-2H7zm0 2H7v26h18zm-9 6a3 3 0 0 1 3 2.82V14a5 5 0 1 1-6 0v-2a3 3 0 0 1 3-3zm0 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6zm0 2a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-6a1 1 0 0 0-1 .88V13.1a5.02 5.02 0 0 1 2 0V12a1 1 0 0 0-1-1z"></path></svg></div></div><div class="m1ec1bsa atm_9s_1txwivl atm_ar_1bp4okc atm_fc_1h6ojuz atm_am_ggq5uc atm_vy_1osqo2v dir dir-ltr"><div class="twad414 atm_7l_jt7fhx atm_9j_1kw7nm4 atm_bx_48h72j atm_c8_2x1prs atm_g3_1jbyh58 atm_fr_11a07z3 dir dir-ltr" id="lock_on_all_bedroom_doors_9998_1114500207597778842-row-title">Cerradura en la puerta del dormitorio</div></div></div></div><div class="_1wadwfl"></div></li><li><div class="rten07p atm_lo_1tcgj5g atm_le_1tcgj5g atm_5j_t94yts dir dir-ltr" id="pdp_v3_home_safety_35_1114500207597778842-0"><div class="f16mr5nx atm_9s_1txwivl dir dir-ltr"><div class="lhg7v4y atm_h0_exct8b dir dir-ltr"><div class="i12mny15 atm_j6_1jbyh58 atm_9s_1txwivl atm_h_1h6ojuz dir dir-ltr"><svg aria-hidden="true" focusable="false" role="presentation" style="display: block; height: 24px; width: 24px; fill: currentcolor;" viewbox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="M16 1a15 15 0 1 1 0 30 15 15 0 0 1 0-30zm0 2a13 13 0 1 0 0 26 13 13 0 0 0 0-26zm-4.9 14a5 5 0 0 0 3.9 3.9v2.03A7 7 0 0 1 9.07 17zm9.8 0h2.03A7 7 0 0 1 17 22.93V20.9a5 5 0 0 0 3.9-3.9zM16 13a3 3 0 1 1 0 6 3 3 0 0 1 0-6zm0 2a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm1-5.93A7 7 0 0 1 22.93 15H20.9a5 5 0 0 0-3.9-3.9zm-2 0v2.03a5 5 0 0 0-3.9 3.9H9.07A7 7 0 0 1 15 9.07zM23 8a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"></path></svg></div></div><div class="m1ec1bsa atm_9s_1txwivl atm_ar_1bp4okc atm_fc_1h6ojuz atm_am_ggq5uc atm_vy_1osqo2v dir dir-ltr"><div class="twad414 atm_7l_jt7fhx atm_9j_1kw7nm4 atm_bx_48h72j atm_c8_2x1prs atm_g3_1jbyh58 atm_fr_11a07z3 dir dir-ltr" id="pdp_v3_home_safety_35_1114500207597778842-0-row-title">Detector de humo</div></div></div></div><div class="_1wadwfl"></div></li><li><div class="rten07p atm_lo_1tcgj5g atm_le_1tcgj5g atm_5j_t94yts dir dir-ltr" id="pdp_v3_home_safety_36_1114500207597778842-0"><div class="f16mr5nx atm_9s_1txwivl dir dir-ltr"><div class="lhg7v4y atm_h0_exct8b dir dir-ltr"><div class="i12mny15 atm_j6_1jbyh58 atm_9s_1txwivl atm_h_1h6ojuz dir dir-ltr"><svg aria-hidden="true" focusable="false" role="presentation" style="display: block; height: 24px; width: 24px; fill: currentcolor;" viewbox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="M25 2a5 5 0 0 1 5 4.78V25a5 5 0 0 1-4.78 5H7a5 5 0 0 1-5-4.78V7a5 5 0 0 1 4.78-5H7zm0 2H7a3 3 0 0 0-3 2.82V25a3 3 0 0 0 2.82 3H25a3 3 0 0 0 3-2.82V7a3 3 0 0 0-2.82-3zM11.1 17a5 5 0 0 0 3.9 3.9v2.03A7 7 0 0 1 9.07 17zm9.8 0h2.03A7 7 0 0 1 17 22.93V20.9a5 5 0 0 0 3.9-3.9zM16 13a3 3 0 1 1 0 6 3 3 0 0 1 0-6zm0 2a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm1-5.93A7 7 0 0 1 22.93 15H20.9a5 5 0 0 0-3.9-3.9zm-2 0v2.03a5 5 0 0 0-3.9 3.9H9.07A7 7 0 0 1 15 9.07zM23 8a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"></path></svg></div></div><div class="m1ec1bsa atm_9s_1txwivl atm_ar_1bp4okc atm_fc_1h6ojuz atm_am_ggq5uc atm_vy_1osqo2v dir dir-ltr"><div class="twad414 atm_7l_jt7fhx atm_9j_1kw7nm4 atm_bx_48h72j atm_c8_2x1prs atm_g3_1jbyh58 atm_fr_11a07z3 dir dir-ltr" id="pdp_v3_home_safety_36_1114500207597778842-0-row-title">Detector de monóxido de carbono</div></div></div></div><div class="_1wadwfl"></div></li></ul></div><div class="_11jhslp"><div class="_87jbxlz"><h3 class="hpipapi atm_7l_1kw7nm4 atm_c8_1x4eueo atm_cs_1kw7nm4 atm_g3_1kw7nm4 atm_gi_idpfg4 atm_l8_idpfg4 atm_kd_idpfg4_pfnrn2 dir dir-ltr" elementtiming="LCP-target" tabindex="-1">Internet y oficina</h3></div><ul class="_2f5j8p" role="list"><li><div class="rten07p atm_lo_1tcgj5g atm_le_1tcgj5g atm_5j_t94yts dir dir-ltr" id="pdp_v3_internet_office_4_1114500207597778842-0"><div class="f16mr5nx atm_9s_1txwivl dir dir-ltr"><div class="lhg7v4y atm_h0_exct8b dir dir-ltr"><div class="i12mny15 atm_j6_1jbyh58 atm_9s_1txwivl atm_h_1h6ojuz dir dir-ltr"><svg aria-hidden="true" focusable="false" role="presentation" style="display: block; height: 24px; width: 24px; fill: currentcolor;" viewbox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="M16 20.33a3.67 3.67 0 1 1 0 7.34 3.67 3.67 0 0 1 0-7.34zm0 2a1.67 1.67 0 1 0 0 3.34 1.67 1.67 0 0 0 0-3.34zM16 15a9 9 0 0 1 8.04 4.96l-1.51 1.51a7 7 0 0 0-13.06 0l-1.51-1.51A9 9 0 0 1 16 15zm0-5.33c4.98 0 9.37 2.54 11.94 6.4l-1.45 1.44a12.33 12.33 0 0 0-20.98 0l-1.45-1.45A14.32 14.32 0 0 1 16 9.66zm0-5.34c6.45 0 12.18 3.1 15.76 7.9l-1.43 1.44a17.64 17.64 0 0 0-28.66 0L.24 12.24c3.58-4.8 9.3-7.9 15.76-7.9z"></path></svg></div></div><div class="m1ec1bsa atm_9s_1txwivl atm_ar_1bp4okc atm_fc_1h6ojuz atm_am_ggq5uc atm_vy_1osqo2v dir dir-ltr"><div class="twad414 atm_7l_jt7fhx atm_9j_1kw7nm4 atm_bx_48h72j atm_c8_2x1prs atm_g3_1jbyh58 atm_fr_11a07z3 dir dir-ltr" id="pdp_v3_internet_office_4_1114500207597778842-0-row-title">Wifi</div></div></div></div><div class="_1wadwfl"></div></li></ul></div><div class="_11jhslp"><div class="_87jbxlz"><h3 class="hpipapi atm_7l_1kw7nm4 atm_c8_1x4eueo atm_cs_1kw7nm4 atm_g3_1kw7nm4 atm_gi_idpfg4 atm_l8_idpfg4 atm_kd_idpfg4_pfnrn2 dir dir-ltr" elementtiming="LCP-target" tabindex="-1">Cocina y comedor</h3></div><ul class="_2f5j8p" role="list"><li><div class="rten07p atm_lo_1tcgj5g atm_le_1tcgj5g atm_5j_t94yts dir dir-ltr" id="pdp_v3_kitchen_dining_8_1114500207597778842-0"><div class="f16mr5nx atm_9s_1txwivl dir dir-ltr"><div class="lhg7v4y atm_h0_exct8b dir dir-ltr"><div class="i12mny15 atm_j6_1jbyh58 atm_9s_1txwivl atm_h_1h6ojuz dir dir-ltr"><svg aria-hidden="true" focusable="false" role="presentation" style="display: block; height: 24px; width: 24px; fill: currentcolor;" viewbox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="M26 1a5 5 0 0 1 5 5c0 6.39-1.6 13.19-4 14.7V31h-2V20.7c-2.36-1.48-3.94-8.07-4-14.36v-.56A5 5 0 0 1 26 1zm-9 0v18.12c2.32.55 4 3 4 5.88 0 3.27-2.18 6-5 6s-5-2.73-5-6c0-2.87 1.68-5.33 4-5.88V1zM2 1h1c4.47 0 6.93 6.37 7 18.5V21H4v10H2zm14 20c-1.6 0-3 1.75-3 4s1.4 4 3 4 3-1.75 3-4-1.4-4-3-4zM4 3.24V19h4l-.02-.96-.03-.95C7.67 9.16 6.24 4.62 4.22 3.36L4.1 3.3zm19 2.58v.49c.05 4.32 1.03 9.13 2 11.39V3.17a3 3 0 0 0-2 2.65zm4-2.65V17.7c.99-2.31 2-7.3 2-11.7a3 3 0 0 0-2-2.83z"></path></svg></div></div><div class="m1ec1bsa atm_9s_1txwivl atm_ar_1bp4okc atm_fc_1h6ojuz atm_am_ggq5uc atm_vy_1osqo2v dir dir-ltr"><div class="twad414 atm_7l_jt7fhx atm_9j_1kw7nm4 atm_bx_48h72j atm_c8_2x1prs atm_g3_1jbyh58 atm_fr_11a07z3 dir dir-ltr" id="pdp_v3_kitchen_dining_8_1114500207597778842-0-row-title">Cocina</div><div class="s9gst5p atm_7l_1he744i atm_h3_1y44olf atm_bx_48h72j atm_w4_1hnarqo atm_c8_km0zk7 atm_g3_18khvle atm_fr_1m9t47k dir dir-ltr">Cocina disponible para el uso de los huéspedes</div></div></div></div><div class="_1wadwfl"></div></li></ul></div><div class="_11jhslp"><div class="_87jbxlz"><h3 class="hpipapi atm_7l_1kw7nm4 atm_c8_1x4eueo atm_cs_1kw7nm4 atm_g3_1kw7nm4 atm_gi_idpfg4 atm_l8_idpfg4 atm_kd_idpfg4_pfnrn2 dir dir-ltr" elementtiming="LCP-target" tabindex="-1">Aparcamiento e instalaciones</h3></div><ul class="_2f5j8p" role="list"><li><div class="rten07p atm_lo_1tcgj5g atm_le_1tcgj5g atm_5j_t94yts dir dir-ltr" id="pdp_v3_parking_facilities_9_1114500207597778842-0"><div class="f16mr5nx atm_9s_1txwivl dir dir-ltr"><div class="lhg7v4y atm_h0_exct8b dir dir-ltr"><div class="i12mny15 atm_j6_1jbyh58 atm_9s_1txwivl atm_h_1h6ojuz dir dir-ltr"><svg aria-hidden="true" focusable="false" role="presentation" style="display: block; height: 24px; width: 24px; fill: currentcolor;" viewbox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="M26 19a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM7 18a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm20.7-5 .41 1.12A4.97 4.97 0 0 1 30 18v9a2 2 0 0 1-2 2h-2a2 2 0 0 1-2-2v-2H8v2a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-9c0-1.57.75-2.96 1.89-3.88L4.3 13H2v-2h3v.15L6.82 6.3A2 2 0 0 1 8.69 5h14.62c.83 0 1.58.52 1.87 1.3L27 11.15V11h3v2h-2.3zM6 25H4v2h2v-2zm22 0h-2v2h2v-2zm0-2v-5a3 3 0 0 0-3-3H7a3 3 0 0 0-3 3v5h24zm-3-10h.56L23.3 7H8.69l-2.25 6H25zm-15 7h12v-2H10v2z"></path></svg></div></div><div class="m1ec1bsa atm_9s_1txwivl atm_ar_1bp4okc atm_fc_1h6ojuz atm_am_ggq5uc atm_vy_1osqo2v dir dir-ltr"><div class="twad414 atm_7l_jt7fhx atm_9j_1kw7nm4 atm_bx_48h72j atm_c8_2x1prs atm_g3_1jbyh58 atm_fr_11a07z3 dir dir-ltr" id="pdp_v3_parking_facilities_9_1114500207597778842-0-row-title">Aparcamiento gratuito en las instalaciones</div></div></div></div><div class="_1wadwfl"></div></li></ul></div><div class="_11jhslp"><div class="_87jbxlz"><h3 class="hpipapi atm_7l_1kw7nm4 atm_c8_1x4eueo atm_cs_1kw7nm4 atm_g3_1kw7nm4 atm_gi_idpfg4 atm_l8_idpfg4 atm_kd_idpfg4_pfnrn2 dir dir-ltr" elementtiming="LCP-target" tabindex="-1">Servicios</h3></div><ul class="_2f5j8p" role="list"><li><div class="rten07p atm_lo_1tcgj5g atm_le_1tcgj5g atm_5j_t94yts dir dir-ltr" id="pdp_v3_services_12_1114500207597778842-0"><div class="f16mr5nx atm_9s_1txwivl dir dir-ltr"><div class="lhg7v4y atm_h0_exct8b dir dir-ltr"><div class="i12mny15 atm_j6_1jbyh58 atm_9s_1txwivl atm_h_1h6ojuz dir dir-ltr"><svg aria-hidden="true" focusable="false" role="presentation" style="display: block; height: 24px; width: 24px; fill: currentcolor;" viewbox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="M13.7 13.93a4 4 0 0 1 5.28.6l.29.37 4.77 6.75a4 4 0 0 1 .6 3.34 4 4 0 0 1-4.5 2.91l-.4-.08-3.48-.93a1 1 0 0 0-.52 0l-3.47.93a4 4 0 0 1-2.94-.35l-.4-.25a4 4 0 0 1-1.2-5.2l.23-.37 4.77-6.75a4 4 0 0 1 .96-.97zm3.75 1.9a2 2 0 0 0-2.98.08l-.1.14-4.84 6.86a2 2 0 0 0 2.05 3.02l.17-.04 4-1.07a1 1 0 0 1 .5 0l3.97 1.06.15.04a2 2 0 0 0 2.13-2.97l-4.95-7.01zM27 12a4 4 0 1 1 0 8 4 4 0 0 1 0-8zM5 12a4 4 0 1 1 0 8 4 4 0 0 1 0-8zm22 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4zM5 14a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm6-10a4 4 0 1 1 0 8 4 4 0 0 1 0-8zm10 0a4 4 0 1 1 0 8 4 4 0 0 1 0-8zM11 6a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm10 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"></path></svg></div></div><div class="m1ec1bsa atm_9s_1txwivl atm_ar_1bp4okc atm_fc_1h6ojuz atm_am_ggq5uc atm_vy_1osqo2v dir dir-ltr"><div class="twad414 atm_7l_jt7fhx atm_9j_1kw7nm4 atm_bx_48h72j atm_c8_2x1prs atm_g3_1jbyh58 atm_fr_11a07z3 dir dir-ltr" id="pdp_v3_services_12_1114500207597778842-0-row-title">Admite mascotas</div><div class="s9gst5p atm_7l_1he744i atm_h3_1y44olf atm_bx_48h72j atm_w4_1hnarqo atm_c8_km0zk7 atm_g3_18khvle atm_fr_1m9t47k dir dir-ltr">Los animales de asistencia siempre están permitidos</div></div></div></div><div class="_1wadwfl"></div></li></ul></div><div class="_11jhslp"><div class="_87jbxlz"><h3 class="hpipapi atm_7l_1kw7nm4 atm_c8_1x4eueo atm_cs_1kw7nm4 atm_g3_1kw7nm4 atm_gi_idpfg4 atm_l8_idpfg4 atm_kd_idpfg4_pfnrn2 dir dir-ltr" elementtiming="LCP-target" tabindex="-1">No incluidos</h3></div><ul class="_2f5j8p" role="list"><li><div class="rten07p atm_lo_1tcgj5g atm_le_1tcgj5g atm_5j_t94yts dir dir-ltr" id="security_camera_9999_1114500207597778842"><div class="f16mr5nx atm_9s_1txwivl dir dir-ltr"><div class="lhg7v4y atm_h0_exct8b dir dir-ltr"><div class="i12mny15 atm_j6_1jbyh58 atm_9s_1txwivl atm_h_1h6ojuz dir dir-ltr"><svg aria-hidden="true" focusable="false" role="presentation" style="display: block; height: 24px; width: 24px; fill: currentcolor;" viewbox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="m2 6.24 2 2V16h3.1a5 5 0 0 1 1.76-2.9l1.43 1.43a3 3 0 1 0 4.18 4.18l1.42 1.43a5 5 0 0 1-2.97 1.78A5 5 0 0 1 8.22 26H4v4H2V20h2v4h4a3 3 0 0 0 2.87-2.13A5 5 0 0 1 7.1 18H4a2 2 0 0 1-2-1.85V6.24zM3.7 2.3l26 26-1.4 1.42-26-26 1.4-1.42zM7.25 3H23a2 2 0 0 1 2 1.85v1.67l5-2v11.96l-5-2V16a2 2 0 0 1-1.85 2h-.91l-2-2H23V5H9.24l-2-2zM28 7.48l-3 1.2v3.64l3 1.2V7.48z"></path></svg></div></div><div class="m1ec1bsa atm_9s_1txwivl atm_ar_1bp4okc atm_fc_1h6ojuz atm_am_ggq5uc atm_vy_1osqo2v dir dir-ltr"><div class="twad414 atm_7l_jt7fhx atm_9j_1kw7nm4 atm_bx_48h72j atm_c8_2x1prs atm_g3_1jbyh58 atm_fr_11a07z3 dir dir-ltr" id="security_camera_9999_1114500207597778842-row-title"><span class="a8jt5op atm_3f_idpfg4 atm_7h_hxbz6r atm_7i_ysn8ba atm_e2_t94yts atm_ks_zryt35 atm_l8_idpfg4 atm_mk_stnw88 atm_vv_1q9ccgz atm_vy_t94yts dir dir-ltr">No disponible: Cámaras de seguridad en los exteriores de la propiedad</span><del aria-hidden="true">Cámaras de seguridad en los exteriores de la propiedad</del></div></div></div></div><div class="_1wadwfl"></div></li><li><div class="rten07p atm_lo_1tcgj5g atm_le_1tcgj5g atm_5j_t94yts dir dir-ltr" id="pdp_unavailable_34_1114500207597778842-0"><div class="f16mr5nx atm_9s_1txwivl dir dir-ltr"><div class="lhg7v4y atm_h0_exct8b dir dir-ltr"><div class="i12mny15 atm_j6_1jbyh58 atm_9s_1txwivl atm_h_1h6ojuz dir dir-ltr"><svg aria-hidden="true" focusable="false" role="presentation" style="display: block; height: 24px; width: 24px; fill: currentcolor;" viewbox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="m2 6.24 2 2V28h19.76l2 2H4a2 2 0 0 1-2-1.85V6.24zM3.7 2.3l26 26-1.4 1.42-26-26 1.4-1.42zM28 2a2 2 0 0 1 2 1.85v21.91l-2-2V4H8.24l-2-2H28zM7.88 12.12l1.52 1.53a6.99 6.99 0 0 0-.4 2.28l1.34-1.35L11.76 16 9.4 18.35c.23.67.57 1.29.98 1.84l2.78-2.78 1.42 1.42-2.78 2.78a6.98 6.98 0 0 0 1.84.99L16 20.24l1.41 1.42L16.07 23h.17a6.98 6.98 0 0 0 2.11-.4l1.53 1.52a9 9 0 0 1-12-12zM16 7a9 9 0 0 1 8.12 12.88l-1.53-1.53a6.99 6.99 0 0 0 .41-2.28l-1.34 1.34L20.24 16l2.35-2.35a6.98 6.98 0 0 0-.98-1.84l-2.78 2.78-1.42-1.42 2.78-2.78a6.98 6.98 0 0 0-1.84-.99L16 11.76l-1.42-1.42L15.93 9h-.17a7 7 0 0 0-2.11.4l-1.53-1.52A8.96 8.96 0 0 1 16 7zm9-1a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"></path></svg></div></div><div class="m1ec1bsa atm_9s_1txwivl atm_ar_1bp4okc atm_fc_1h6ojuz atm_am_ggq5uc atm_vy_1osqo2v dir dir-ltr"><div class="twad414 atm_7l_jt7fhx atm_9j_1kw7nm4 atm_bx_48h72j atm_c8_2x1prs atm_g3_1jbyh58 atm_fr_11a07z3 dir dir-ltr" id="pdp_unavailable_34_1114500207597778842-0-row-title"><span class="a8jt5op atm_3f_idpfg4 atm_7h_hxbz6r atm_7i_ysn8ba atm_e2_t94yts atm_ks_zryt35 atm_l8_idpfg4 atm_mk_stnw88 atm_vv_1q9ccgz atm_vy_t94yts dir dir-ltr">No disponible: Secadora</span><del aria-hidden="true">Secadora</del></div></div></div></div><div class="_1wadwfl"></div></li><li><div class="rten07p atm_lo_1tcgj5g atm_le_1tcgj5g atm_5j_t94yts dir dir-ltr" id="pdp_unavailable_5_1114500207597778842-0"><div class="f16mr5nx atm_9s_1txwivl dir dir-ltr"><div class="lhg7v4y atm_h0_exct8b dir dir-ltr"><div class="i12mny15 atm_j6_1jbyh58 atm_9s_1txwivl atm_h_1h6ojuz dir dir-ltr"><svg aria-hidden="true" focusable="false" role="presentation" style="display: block; height: 24px; width: 24px; fill: currentcolor;" viewbox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="m15 19.24 2 2v3.42l5.03 2.9-1 1.73L17 26.97V31h-2v-4.03l-4.03 2.32-1-1.73 5.03-2.9v-5.42zM3.7 2.3l26 26-1.4 1.42-26-26 1.4-1.42zm-.73 14.27L8 19.46l4.58-2.64 1.46 1.46L9 21.2V27H7v-4.65l-3.49 2.02-1-1.74L6 20.62l-4.03-2.33 1-1.73zm26.06 0 1 1.73L26 20.62l3.49 2.01-.96 1.66-5.23-5.23.7.4 5.03-2.9zM25 5v4.65l3.49-2.02 1 1.74L26 11.38l4.03 2.33-1 1.73-5.03-2.9-4.58 2.64-1.46-1.47 5.04-2.9V5h2zM3.47 7.7l5.22 5.24-.69-.4-5.03 2.9-1-1.73L6 11.38 2.51 9.37l.96-1.66zM17 1v4.03l4.03-2.32 1 1.73L17 7.34v5.42l-2-2V7.34l-5.03-2.9 1-1.73L15 5.03V1h2z"></path></svg></div></div><div class="m1ec1bsa atm_9s_1txwivl atm_ar_1bp4okc atm_fc_1h6ojuz atm_am_ggq5uc atm_vy_1osqo2v dir dir-ltr"><div class="twad414 atm_7l_jt7fhx atm_9j_1kw7nm4 atm_bx_48h72j atm_c8_2x1prs atm_g3_1jbyh58 atm_fr_11a07z3 dir dir-ltr" id="pdp_unavailable_5_1114500207597778842-0-row-title"><span class="a8jt5op atm_3f_idpfg4 atm_7h_hxbz6r atm_7i_ysn8ba atm_e2_t94yts atm_ks_zryt35 atm_l8

In [23]:
amenities_list = [i.text.strip() for i in caract.find_all('li')]
amenities_list

['Lavadora',
 'TV',
 'Cerradura en la puerta del dormitorio',
 'Detector de humo',
 'Detector de monóxido de carbono',
 'Wifi',
 'CocinaCocina disponible para el uso de los huéspedes',
 'Aparcamiento gratuito en las instalaciones',
 'Admite mascotasLos animales de asistencia siempre están permitidos',
 'No disponible: Cámaras de seguridad en los exteriores de la propiedadCámaras de seguridad en los exteriores de la propiedad',
 'No disponible: SecadoraSecadora',
 'No disponible: Aire acondicionadoAire acondicionado',
 'No disponible: Servicios básicosServicios básicos',
 'No disponible: CalefacciónCalefacción',
 'No disponible: Agua calienteAgua caliente']

In [24]:
#Lista para almacenar elementos con "No disponible"
not_available = [i for i in amenities_list if "No disponible" in i]

#Lista para almacenar elementos sin "No disponible"
available = [i for i in amenities_list if "No disponible" not in i]

print("Elementos disponibles:", available)
print("Elementos no disponibles:", not_available)

Elementos disponibles: ['Lavadora', 'TV', 'Cerradura en la puerta del dormitorio', 'Detector de humo', 'Detector de monóxido de carbono', 'Wifi', 'CocinaCocina disponible para el uso de los huéspedes', 'Aparcamiento gratuito en las instalaciones', 'Admite mascotasLos animales de asistencia siempre están permitidos']
Elementos no disponibles: ['No disponible: Cámaras de seguridad en los exteriores de la propiedadCámaras de seguridad en los exteriores de la propiedad', 'No disponible: SecadoraSecadora', 'No disponible: Aire acondicionadoAire acondicionado', 'No disponible: Servicios básicosServicios básicos', 'No disponible: CalefacciónCalefacción', 'No disponible: Agua calienteAgua caliente']

Localizar cada oferta de una página y listamos

In [30]:
url = "https://www.airbnb.es/s/Palma-de-Mallorca--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-04-01&monthly_length=3&monthly_end_date=2024-07-01&price_filter_input_type=0&channel=EXPLORE&query=Palma%20de%20Mallorca%2C%20Espa%C3%B1a&place_id=ChIJBx4GBoeUlxIRUtQsMHk3UuE&date_picker_type=calendar&source=structured_search_input_header&search_type=autocomplete_click"

In [31]:
browser.get(url)

In [32]:
html = browser.page_source
html

'<html lang="es" dir="ltr" data-is-hyperloop="true" data-hyperloop-version="2" style="--vh: 6.5px; --vw: 9.96px; --vw-unitless: 996;" class="dir native v1oc6b3k vgnbcm1 v1agkal2 vqw89vp vlugpmm g5l85gq"><head><style>.LGLeeN-keyboard-shortcuts-view{display:-webkit-box;display:-webkit-flex;display:-moz-box;display:-ms-flexbox;display:flex}.LGLeeN-keyboard-shortcuts-view table,.LGLeeN-keyboard-shortcuts-view tbody,.LGLeeN-keyboard-shortcuts-view td,.LGLeeN-keyboard-shortcuts-view tr{background:inherit;border:none;margin:0;padding:0}.LGLeeN-keyboard-shortcuts-view table{display:table}.LGLeeN-keyboard-shortcuts-view tr{display:table-row}.LGLeeN-keyboard-shortcuts-view td{-moz-box-sizing:border-box;box-sizing:border-box;display:table-cell;color:#000;padding:6px;vertical-align:middle;white-space:nowrap}.LGLeeN-keyboard-shortcuts-view td:first-child{text-align:end}.LGLeeN-keyboard-shortcuts-view td kbd{background-color:#e8eaed;border-radius:2px;border:none;-moz-box-sizing:border-box;box-sizing:border-box;color:inherit;display:inline-block;font-family:Google Sans Text,Roboto,Arial,sans-serif;line-height:16px;margin:0 2px;min-height:20px;min-width:20px;padding:2px 4px;position:relative;text-align:center}\n</style><style>.gm-control-active>img{-webkit-box-sizing:content-box;box-sizing:content-box;display:none;left:50%;pointer-events:none;position:absolute;top:50%;-webkit-transform:translate(-50%,-50%);-ms-transform:translate(-50%,-50%);-o-transform:translate(-50%,-50%);transform:translate(-50%,-50%)}.gm-control-active>img:nth-child(1){display:block}.gm-control-active:focus>img:nth-child(1),.gm-control-active:hover>img:nth-child(1),.gm-control-active:active>img:nth-child(1),.gm-control-active:disabled>img:nth-child(1){display:none}.gm-control-active:focus>img:nth-child(2),.gm-control-active:hover>img:nth-child(2){display:block}.gm-control-active:active>img:nth-child(3){display:block}.gm-control-active:disabled>img:nth-child(4){display:block}sentinel{}\n</style><link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Google+Sans:400,500,700|Google+Sans+Text:400&amp;lang=es"><link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Google+Sans+Text:400&amp;text=%E2%86%90%E2%86%92%E2%86%91%E2%86%93&amp;lang=es"><style>.gm-ui-hover-effect{opacity:.6}.gm-ui-hover-effect:hover{opacity:1}.gm-ui-hover-effect>span{background-color:#000}@media (forced-colors:active),(prefers-contrast:more){.gm-ui-hover-effect>span{background-color:ButtonText}}sentinel{}\n</style><style>.gm-style .gm-style-cc a,.gm-style .gm-style-cc button,.gm-style .gm-style-cc span,.gm-style .gm-style-mtc div{font-size:10px;-webkit-box-sizing:border-box;box-sizing:border-box}.gm-style .gm-style-cc a,.gm-style .gm-style-cc button,.gm-style .gm-style-cc span{outline-offset:3px}sentinel{}\n</style><style>@media print {  .gm-style .gmnoprint, .gmnoprint {    display:none  }}@media screen {  .gm-style .gmnoscreen, .gmnoscreen {    display:none  }}</style><style>.gm-style-moc{background-color:rgba(0,0,0,.45);pointer-events:none;text-align:center;-webkit-transition:opacity ease-in-out;-o-transition:opacity ease-in-out;transition:opacity ease-in-out}.gm-style-mot{color:white;font-family:Roboto,Arial,sans-serif;font-size:22px;margin:0;position:relative;top:50%;-o-transform:translateY(-50%);transform:translateY(-50%);-webkit-transform:translateY(-50%);-ms-transform:translateY(-50%)}sentinel{}\n</style><style>.gm-style img{max-width: none;}.gm-style {font: 400 11px Roboto, Arial, sans-serif; text-decoration: none;}</style><meta charset="utf-8"><meta name="locale" content="es"><meta name="google" content="notranslate"><meta id="csrf-param-meta-tag" name="csrf-param" content="authenticity_token"><meta id="csrf-token-meta-tag" name="csrf-token" content="null"><meta id="english-canonical-url" content=""><meta name="twitter:widgets:csp" content="on"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="application-name" content="Airbnb"><meta name="apple-mobile-web-app-title" content="Airbnb"><meta name="theme-color" content="#ffffff"><meta name="msapplication-navbutton-color" content="#ffffff"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="msapplication-starturl" content="/?utm_source=homescreen"><link href="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/apps/core-guest-spa/client.3a2af6a5bd.css" rel="stylesheet" type="text/css" media="all" crossorigin="anonymous"><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-788919195&amp;l=dataLayer&amp;cx=c"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/destination?id=DC-4620401&amp;l=dataLayer&amp;cx=c"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-1023009977&amp;l=dataLayer&amp;cx=c"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-2P6Q8PGG16&amp;l=dataLayer&amp;cx=c"></script><script defer="" src="https://www.googletagmanager.com/gtm.js?id=GTM-46MK"></script><script src="https://connect.facebook.net/es_ES/sdk.js?hash=de39385d1413973ab7f943bddcad325e" async="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/metroRequire.ae703c8f7e.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/shims_post_modules.3a508a05ae.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/airmetro/src/browser/asyncRequire.850c368e1e.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/coreV2.d6f9f63d25.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/routeHandler.eb80466977.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/4199.5e3bb90aec.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/6c27.fa954d98a5.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/8bc1.8f6a9e34a1.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/10f8.9117338e7d.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/node_modules/moment/locale/es.2078639028.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/apps/core-guest-spa/initializer.c6c1050f75.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/guest-header/query/HeaderQuery.prepare.d7f2b63b5c.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/08bb.14cb15ead3.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/c716.39066a3328.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/niobe/minimalist/index.e2c6bf6af5.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/7feb.f75ae7a452.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/9ff5.ac1411f58e.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/ca89.69226a1f9a.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/b0df.94a530809a.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/0d90.ade6c80b29.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/stays-search/routes/StaysSearchRoute/StaysSearchRoute.be5666f454.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/stays-search/routes/StaysSearchRoute/StaysSearchRoute.prepare.b8d2dfcfb6.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/f4c9f.a8028461f8.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/0f40.653b543916.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/a2ec.121a9da08c.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/4857.55b4640d65.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/e008.b6070a7705.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/e3a3.8014d0c86b.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/1cc0.9a9004ba18.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/2b64.48dfb6f865.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/common/19be.ec5149f10f.js" defer="" crossorigin="anonymous"></script><script src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/core-guest-loop/apps/core-guest-spa/client.6cef39f3f1.js" defer="" crossorigin="anonymous"></script><script>(function() {\n  // pg_pixel is no-op now.\n})()</script><script>(function(){function a(c){if(window._errorReportingInitialized)return void window.removeEventListener("error",a);const{error:d}=c;if(!d)return;const e=c.message||d.message,f=/Requiring unknown module/.test(e)?1/100:1/10;if(Math.random()>f)return;const{locale:g,tracking_context:h}=window[Symbol.for("__ global cache key __")]?.["string | airbnb-bootstrap-data"]?.["_bootstrap-layout-init"]??{},i=g||navigator.language,j=location.pathname,k="undefined"==typeof window?{sampleRate:f+""}:{tags:{loggingSource:"browser",sampleRate:f+""}};fetch("https://notify.bugsnag.com/",{headers:{"Bugsnag-Payload-Version":"5"},body:JSON.stringify({apiKey:"e393bc25e52fe915ffb56c14ddf2ff1b",payloadVersion:b,notifier:{name:"Bugsnag JavaScript",version:"0.0.5-AirbnbUnhandledBufferedErrorCustomFetch",url:""},events:[{exceptions:[{errorClass:d.name,message:e,stacktrace:[{file:c.filename,lineNumber:c.lineno,columnNumber:c.colno}],type:"browserjs"}],request:{url:location.href},context:j,groupingHash:d.name.concat("-",e,"-",j),unhandled:!0,app:{releaseStage:h?.environment},device:{time:new Date,userAgent:navigator.userAgent},metaData:{infra:{app_name:h?.app,is_buffered_error:!0,loop_name:h?.controller,locale:i,service_worker_url:navigator.serviceWorker?.controller?.scriptURL},...k}}]}),method:"POST"})}const b="5";"undefined"!=typeof window&&window.addEventListener("error",a)})();</script><script>\n// FID init code.\n(function(a,b){function c(a){l.push(a),f()}function d(a,b){i||(i=b,j=a,k=new Date,f())}function e(){i&&(i=null,j=null,k=null)}function f(){0<=j&&j<k-n&&(l.forEach(a=>{a(j,i)}),l=[])}function g(c,e){function f(){d(c,e),h()}function g(){h()}function h(){b(o,f,m),b(p,g,m)}a(o,f,m),a(p,g,m)}function h(a){if(a.cancelable){const b=1e12<a.timeStamp,c=b?new Date:performance.now(),e=c-a.timeStamp;"pointerdown"===a.type?g(e,a):d(e,a)}}let i,j,k,l=[];const m={passive:!0,capture:!0},n=new Date,o="pointerup",p="pointercancel";(function(a){["click","mousedown","keydown","touchstart","pointerdown"].forEach(b=>{a(b,h,m)})})(a),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=c,self.perfMetrics.clearFirstInputDelay=e})(addEventListener,removeEventListener);\n// TTFMP Polyfill code.\n(function(a){function b(){const c=document.getElementById(i);h=0,c?g===c?e=a(b):"IMG"!==c.tagName||c.complete?a(function(){const a=performance.now();g=c,f?f(a):h=a,performance.measure&&performance.measure("TTFMP")}):e=a(b):e=a(b)}function c(a){h?a(h):f=a}function d(){cancelAnimationFrame(e)}let e,f,g,h;const i="FMP-target";e=a(b),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstMeaningfulPaint=c,self.perfMetrics.startSearchingForFirstMeaningfulPaint=function(){g=document.getElementById(i),b()},self.perfMetrics.stopSearchingForFirstMeaningfulPaint=d})(requestAnimationFrame);\n// LCP Polyfill code\n(function(a,b,c){function d(a,b,c){(b>o*(1+q)||!document.body.contains(m))&&(o=b,p=c,m=a,x?.(p,m,o))}function e(a,b){if("IMG"!==a.tagName)b();else{const d=()=>c(b);a.complete?d():a.addEventListener("load",d,{once:!0})}}function f(a){w?.observe(a)}function g(a){return u.includes(a.tagName)||a.hasAttribute("data-lcp-candidate")}function h(){if(t)if(s)v||(v={IMG:document.getElementsByTagName("img"),H1:document.getElementsByTagName("h1"),H2:document.getElementsByTagName("h2"),H3:document.getElementsByTagName("h3"),H4:document.getElementsByTagName("h4"),H5:document.getElementsByTagName("h5"),SVG:document.getElementsByTagName("svg")}),u.forEach(a=>{Array.from(v[a]).forEach(a=>{f(a)})}),setTimeout(h,50);else{!r&&document.body&&(r=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,a=>g(a)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT));for(let a;a=r?.nextNode();)f(a);c(h)}}function i(){n=performance.now(),o=0,p=0,w=new IntersectionObserver(a=>{a.filter(a=>a.isIntersecting).forEach(a=>{const b=a.target,{width:c,height:f}=a.intersectionRect;e(b,()=>{const a=performance.now();d(b,c*f,a)})})}),c(h),y.forEach(b=>{a(b,j,z)})}function j(a){const b=a.target;"scroll"===a.type&&("expand-trigger"===b?.className||"contract-trigger"===b?.className)||0===o||250>performance.now()-n||k()}function k(){w?.disconnect(),y.forEach(a=>{b(a,j,z)}),t=!1,w=null}function l(a){x=a,0!==p&&x(p,m,o)}let m,n=0,o=0,p=0;const q=666778e-9;let r,s=!1,t=!0;const u=["IMG","H1","H2","H3","H4","H5","SVG"];let v,w,x;const y=["click","mousedown","keydown","touchstart","pointerdown","scroll"],z={passive:!0,capture:!0};i(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onLargestContentfulPaint=l,self.perfMetrics.startSearchingForLargestContentfulPaint=i.bind(null,!1),self.perfMetrics.stopSearchingForLargestContentfulPaint=k,self.perfMetrics.markIsHydratedForLargestContentfulPaint=()=>{s=!0},self.perfMetrics.registerLCPCandidate=f,self.perfMetrics.inspectLCPTarget=()=>m})(addEventListener,removeEventListener,requestAnimationFrame);\n// INP init code.\n(function(a){var b=Math.max,c=Math.min;function d(){return null==t?null==performance.interactionCount?0:performance.interactionCount:u}function e(){const a=d()-n;return a}function f(){const a=c(r.length-1,Math.floor(e()/50));return r[a]}function g(){"PerformanceObserver"in window&&PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("event")&&(y(),m=new PerformanceObserver(a=>{Promise.resolve().then(()=>{const b=a.getEntries();i(b)})}),m.observe({type:"event",buffered:!0,durationThreshold:40}),m.observe({type:"first-input",buffered:!0}),a("visibilitychange",j,!0),a("pageshow",k,!0))}function h(a){if(null==a.interactionId)return;const c=r[r.length-1],d=s.get(a.interactionId);if(null!=d||r.length<q||a.duration>c.latency){if(null!=d)d.entries.push(a),d.latency=b(d.latency,a.duration);else{const b={id:a.interactionId,latency:a.duration,entries:[a]};r.push(b),s.set(a.interactionId,b)}r.sort((c,a)=>a.latency-c.latency),r.splice(q).forEach(a=>{s.delete(a.id)})}}function i(a){a.forEach(a=>{a.interactionId&&h(a)});const b=f();b&&b.latency!==o.value&&(o.value=b.latency,o.entries=b.entries,l())}function j(){null==m||"hidden"===document.visibilityState&&(i(m.takeRecords()),0>o.value&&0<e()&&(o.value=0,o.entries=[]),l())}function k(a){a.persisted&&(r=[],s.clear(),n=d(),o.value=-1,o.entries=[])}function l(){p&&p(o.value,o.entries)}let m,n=0;const o={value:-1,entries:[]};let p;const q=10;let r=[];const s=new Map;let t,u=0,v=1/0,w=0;const x=a=>{a.forEach(a=>{a.interactionId&&(v=c(v,a.interactionId),w=b(w,a.interactionId),u=w?(w-v)/7+1:0)})},y=()=>{"interactionCount"in performance||null!=t||PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("event")&&(t=new PerformanceObserver(a=>{Promise.resolve().then(()=>{x(a.getEntries())})}),t.observe({type:"event",buffered:!0,durationThreshold:0}))};g(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onInp=function(a){0<=o.value?a(o.value,o.entries):p=a},self.perfMetrics.clearInp=function(){r=[],s.clear(),n=0,u=0,v=1/0,w=0,o.value=-1,o.entries=[]}})(addEventListener);\n</script><script>((a,b,c,d)=>{if(d.supports("(font: -apple-system-body) and (-webkit-touch-callout: default)")){const d=a.createElement("div");d.setAttribute("style","font: -apple-system-body"),b.appendChild(d);const e=c(d);"17px"===e.fontSize&&b.style.setProperty("--root-font-size","16px"),b.removeChild(d)}})(document,document.documentElement,getComputedStyle,CSS);</script><link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="Airbnb"><link rel="apple-touch-icon" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-76x76-3b313d93b1b5823293524b9764352ac9.png"><link rel="apple-touch-icon" sizes="76x76" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-76x76-3b313d93b1b5823293524b9764352ac9.png"><link rel="apple-touch-icon" sizes="120x120" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-120x120-52b1adb4fe3a8f825fc4b143de12ea4b.png"><link rel="apple-touch-icon" sizes="152x152" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-152x152-7b7c6444b63d8b6ebad9dae7169e5ed6.png"><link rel="apple-touch-icon" sizes="180x180" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-180x180-bcbe0e3960cd084eb8eaf1353cf3c730.png"><link rel="icon" sizes="192x192" href="https://a0.muscache.com/airbnb/static/icons/android-icon-192x192-c0465f9f0380893768972a31a614b670.png"><link rel="shortcut icon" sizes="76x76" type="image/x-icon" href="https://a0.muscache.com/airbnb/static/logotype_favicon-21cc8e6c6a2cca43f061d2dcabdf6e58.ico"><link rel="mask-icon" href="https://a0.muscache.com/airbnb/static/icons/airbnb-0611901eac33ccfa5e93d793a2e21f09.svg" color="#FF5A5F"><link href="https://a0.muscache.com/airbnb/static/packages/dls/dls-lite_cereal-47d27fa833e062fe3413637eb751001f.css" rel="stylesheet" type="text/css" media="all" crossorigin="anonymous"><meta content="width=device-width, initial-scale=1, viewport-fit=cover" name="viewport"><style data-aphrodite="true" id="aphrodite" type="text/css">._vuzcgs{-webkit-box-pack:end !important;-ms-flex-pack:end !important;-webkit-box-align:center !important;-ms-flex-align:center !important;position:relative !important;display:-webkit-box !important;display:-moz-box !important;display:-ms-flexbox !important;display:-webkit-flex !important;display:flex !important;-webkit-align-items:center !important;align-items:center !important;-webkit-justify-content:flex-end !important;justify-content:flex-end !important;height:80px !important;}._176ugpa{-webkit-box-pack:end !important;-ms-flex-pack:end !important;display:-webkit-box !important;display:-moz-box !important;display:-ms-flexbox !important;display:-webkit-flex !important;display:flex !important;-webkit-flex:auto !important;-ms-flex:1 1 auto !important;flex:auto !important;-webkit-justify

In [33]:
soup = bs(html, 'lxml')
soup

<html class="dir native v1oc6b3k vgnbcm1 v1agkal2 vqw89vp vlugpmm g5l85gq" data-hyperloop-version="2" data-is-hyperloop="true" dir="ltr" lang="es" style="--vh: 6.5px; --vw: 9.96px; --vw-unitless: 996;"><head><style>.LGLeeN-keyboard-shortcuts-view{display:-webkit-box;display:-webkit-flex;display:-moz-box;display:-ms-flexbox;display:flex}.LGLeeN-keyboard-shortcuts-view table,.LGLeeN-keyboard-shortcuts-view tbody,.LGLeeN-keyboard-shortcuts-view td,.LGLeeN-keyboard-shortcuts-view tr{background:inherit;border:none;margin:0;padding:0}.LGLeeN-keyboard-shortcuts-view table{display:table}.LGLeeN-keyboard-shortcuts-view tr{display:table-row}.LGLeeN-keyboard-shortcuts-view td{-moz-box-sizing:border-box;box-sizing:border-box;display:table-cell;color:#000;padding:6px;vertical-align:middle;white-space:nowrap}.LGLeeN-keyboard-shortcuts-view td:first-child{text-align:end}.LGLeeN-keyboard-shortcuts-view td kbd{background-color:#e8eaed;border-radius:2px;border:none;-moz-box-sizing:border-box;box-sizing:border-box;color:inherit;display:inline-block;font-family:Google Sans Text,Roboto,Arial,sans-serif;line-height:16px;margin:0 2px;min-height:20px;min-width:20px;padding:2px 4px;position:relative;text-align:center}
</style><style>.gm-control-active>img{-webkit-box-sizing:content-box;box-sizing:content-box;display:none;left:50%;pointer-events:none;position:absolute;top:50%;-webkit-transform:translate(-50%,-50%);-ms-transform:translate(-50%,-50%);-o-transform:translate(-50%,-50%);transform:translate(-50%,-50%)}.gm-control-active>img:nth-child(1){display:block}.gm-control-active:focus>img:nth-child(1),.gm-control-active:hover>img:nth-child(1),.gm-control-active:active>img:nth-child(1),.gm-control-active:disabled>img:nth-child(1){display:none}.gm-control-active:focus>img:nth-child(2),.gm-control-active:hover>img:nth-child(2){display:block}.gm-control-active:active>img:nth-child(3){display:block}.gm-control-active:disabled>img:nth-child(4){display:block}sentinel{}
</style><link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Google+Sans:400,500,700|Google+Sans+Text:400&amp;lang=es" rel="stylesheet" type="text/css"/><link href="https://fonts.googleapis.com/css?family=Google+Sans+Text:400&amp;text=%E2%86%90%E2%86%92%E2%86%91%E2%86%93&amp;lang=es" rel="stylesheet" type="text/css"/><style>.gm-ui-hover-effect{opacity:.6}.gm-ui-hover-effect:hover{opacity:1}.gm-ui-hover-effect>span{background-color:#000}@media (forced-colors:active),(prefers-contrast:more){.gm-ui-hover-effect>span{background-color:ButtonText}}sentinel{}
</style><style>.gm-style .gm-style-cc a,.gm-style .gm-style-cc button,.gm-style .gm-style-cc span,.gm-style .gm-style-mtc div{font-size:10px;-webkit-box-sizing:border-box;box-sizing:border-box}.gm-style .gm-style-cc a,.gm-style .gm-style-cc button,.gm-style .gm-style-cc span{outline-offset:3px}sentinel{}
</style><style>@media print {  .gm-style .gmnoprint, .gmnoprint {    display:none  }}@media screen {  .gm-style .gmnoscreen, .gmnoscreen {    display:none  }}</style><style>.gm-style-moc{background-color:rgba(0,0,0,.45);pointer-events:none;text-align:center;-webkit-transition:opacity ease-in-out;-o-transition:opacity ease-in-out;transition:opacity ease-in-out}.gm-style-mot{color:white;font-family:Roboto,Arial,sans-serif;font-size:22px;margin:0;position:relative;top:50%;-o-transform:translateY(-50%);transform:translateY(-50%);-webkit-transform:translateY(-50%);-ms-transform:translateY(-50%)}sentinel{}
</style><style>.gm-style img{max-width: none;}.gm-style {font: 400 11px Roboto, Arial, sans-serif; text-decoration: none;}</style><meta charset="utf-8"/><meta content="es" name="locale"/><meta content="notranslate" name="google"/><meta content="authenticity_token" id="csrf-param-meta-tag" name="csrf-param"/><meta content="null" id="csrf-token-meta-tag" name="csrf-token"/><meta content="" id="english-canonical-url"/><meta content="on" name="twitter:widgets:csp"/><meta content="yes" name="mobile-web-app-capable"/><meta content="yes" name="apple-mobile-web-app-capable"/><meta content="Airbnb" name="application-name"/><meta content="Airbnb" name="apple-mobile-web-app-title"/><meta content="#ffffff" name="theme-color"/><meta content="#ffffff" name="msapplication-navbutton-color"/><meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"/><meta content="/?utm_source=homescreen" name="msapplication-starturl"/><link crossorigin="anonymous" href="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/apps/core-guest-spa/client.3a2af6a5bd.css" media="all" rel="stylesheet" type="text/css"/><script async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-788919195&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/destination?id=DC-4620401&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-1023009977&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-2P6Q8PGG16&amp;l=dataLayer&amp;cx=c" type="text/javascript"></script><script defer="" src="https://www.googletagmanager.com/gtm.js?id=GTM-46MK"></script><script async="" crossorigin="anonymous" src="https://connect.facebook.net/es_ES/sdk.js?hash=de39385d1413973ab7f943bddcad325e"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/metroRequire.ae703c8f7e.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/shims_post_modules.3a508a05ae.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/airmetro/src/browser/asyncRequire.850c368e1e.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/hyperloop-browser/coreV2.d6f9f63d25.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/routeHandler.eb80466977.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/4199.5e3bb90aec.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/6c27.fa954d98a5.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/8bc1.8f6a9e34a1.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/10f8.9117338e7d.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/node_modules/moment/locale/es.2078639028.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/core-guest-loop/apps/core-guest-spa/initializer.c6c1050f75.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/guest-header/query/HeaderQuery.prepare.d7f2b63b5c.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/08bb.14cb15ead3.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/c716.39066a3328.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/niobe/minimalist/index.e2c6bf6af5.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/7feb.f75ae7a452.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/9ff5.ac1411f58e.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/ca89.69226a1f9a.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/b0df.94a530809a.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/0d90.ade6c80b29.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/stays-search/routes/StaysSearchRoute/StaysSearchRoute.be5666f454.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/frontend/stays-search/routes/StaysSearchRoute/StaysSearchRoute.prepare.b8d2dfcfb6.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/f4c9f.a8028461f8.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/0f40.653b543916.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/a2ec.121a9da08c.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/4857.55b4640d65.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/e008.b6070a7705.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/e3a3.8014d0c86b.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/1cc0.9a9004ba18.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/2b64.48dfb6f865.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/common/19be.ec5149f10f.js"></script><script crossorigin="anonymous" defer="" src="https://a0.muscache.com/airbnb/static/packages/web/es/frontend/core-guest-loop/apps/core-guest-spa/client.6cef39f3f1.js"></script><script>(function() {
  // pg_pixel is no-op now.
})()</script><script>(function(){function a(c){if(window._errorReportingInitialized)return void window.removeEventListener("error",a);const{error:d}=c;if(!d)return;const e=c.message||d.message,f=/Requiring unknown module/.test(e)?1/100:1/10;if(Math.random()>f)return;const{locale:g,tracking_context:h}=window[Symbol.for("__ global cache key __")]?.["string | airbnb-bootstrap-data"]?.["_bootstrap-layout-init"]??{},i=g||navigator.language,j=location.pathname,k="undefined"==typeof window?{sampleRate:f+""}:{tags:{loggingSource:"browser",sampleRate:f+""}};fetch("https://notify.bugsnag.com/",{headers:{"Bugsnag-Payload-Version":"5"},body:JSON.stringify({apiKey:"e393bc25e52fe915ffb56c14ddf2ff1b",payloadVersion:b,notifier:{name:"Bugsnag JavaScript",version:"0.0.5-AirbnbUnhandledBufferedErrorCustomFetch",url:""},events:[{exceptions:[{errorClass:d.name,message:e,stacktrace:[{file:c.filename,lineNumber:c.lineno,columnNumber:c.colno}],type:"browserjs"}],request:{url:location.href},context:j,groupingHash:d.name.concat("-",e,"-",j),unhandled:!0,app:{releaseStage:h?.environment},device:{time:new Date,userAgent:navigator.userAgent},metaData:{infra:{app_name:h?.app,is_buffered_error:!0,loop_name:h?.controller,locale:i,service_worker_url:navigator.serviceWorker?.controller?.scriptURL},...k}}]}),method:"POST"})}const b="5";"undefined"!=typeof window&&window.addEventListener("error",a)})();</script><script>
// FID init code.
(function(a,b){function c(a){l.push(a),f()}function d(a,b){i||(i=b,j=a,k=new Date,f())}function e(){i&&(i=null,j=null,k=null)}function f(){0<=j&&j<k-n&&(l.forEach(a=>{a(j,i)}),l=[])}function g(c,e){function f(){d(c,e),h()}function g(){h()}function h(){b(o,f,m),b(p,g,m)}a(o,f,m),a(p,g,m)}function h(a){if(a.cancelable){const b=1e12<a.timeStamp,c=b?new Date:performance.now(),e=c-a.timeStamp;"pointerdown"===a.type?g(e,a):d(e,a)}}let i,j,k,l=[];const m={passive:!0,capture:!0},n=new Date,o="pointerup",p="pointercancel";(function(a){["click","mousedown","keydown","touchstart","pointerdown"].forEach(b=>{a(b,h,m)})})(a),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=c,self.perfMetrics.clearFirstInputDelay=e})(addEventListener,removeEventListener);
// TTFMP Polyfill code.
(function(a){function b(){const c=document.getElementById(i);h=0,c?g===c?e=a(b):"IMG"!==c.tagName||c.complete?a(function(){const a=performance.now();g=c,f?f(a):h=a,performance.measure&&performance.measure("TTFMP")}):e=a(b):e=a(b)}function c(a){h?a(h):f=a}function d(){cancelAnimationFrame(e)}let e,f,g,h;const i="FMP-target";e=a(b),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstMeaningfulPaint=c,self.perfMetrics.startSearchingForFirstMeaningfulPaint=function(){g=document.getElementById(i),b()},self.perfMetrics.stopSearchingForFirstMeaningfulPaint=d})(requestAnimationFrame);
// LCP Polyfill code
(function(a,b,c){function d(a,b,c){(b>o*(1+q)||!document.body.contains(m))&&(o=b,p=c,m=a,x?.(p,m,o))}function e(a,b){if("IMG"!==a.tagName)b();else{const d=()=>c(b);a.complete?d():a.addEventListener("load",d,{once:!0})}}function f(a){w?.observe(a)}function g(a){return u.includes(a.tagName)||a.hasAttribute("data-lcp-candidate")}function h(){if(t)if(s)v||(v={IMG:document.getElementsByTagName("img"),H1:document.getElementsByTagName("h1"),H2:document.getElementsByTagName("h2"),H3:document.getElementsByTagName("h3"),H4:document.getElementsByTagName("h4"),H5:document.getElementsByTagName("h5"),SVG:document.getElementsByTagName("svg")}),u.forEach(a=>{Array.from(v[a]).forEach(a=>{f(a)})}),setTimeout(h,50);else{!r&&document.body&&(r=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,a=>g(a)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT));for(let a;a=r?.nextNode();)f(a);c(h)}}function i(){n=performance.now(),o=0,p=0,w=new IntersectionObserver(a=>{a.filter(a=>a.isIntersecting).forEach(a=>{const b=a.target,{width:c,height:f}=a.intersectionRect;e(b,()=>{const a=performance.now();d(b,c*f,a)})})}),c(h),y.forEach(b=>{a(b,j,z)})}function j(a){const b=a.target;"scroll"===a.type&&("expand-trigger"===b?.className||"contract-trigger"===b?.className)||0===o||250>performance.now()-n||k()}function k(){w?.disconnect(),y.forEach(a=>{b(a,j,z)}),t=!1,w=null}function l(a){x=a,0!==p&&x(p,m,o)}let m,n=0,o=0,p=0;const q=666778e-9;let r,s=!1,t=!0;const u=["IMG","H1","H2","H3","H4","H5","SVG"];let v,w,x;const y=["click","mousedown","keydown","touchstart","pointerdown","scroll"],z={passive:!0,capture:!0};i(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onLargestContentfulPaint=l,self.perfMetrics.startSearchingForLargestContentfulPaint=i.bind(null,!1),self.perfMetrics.stopSearchingForLargestContentfulPaint=k,self.perfMetrics.markIsHydratedForLargestContentfulPaint=()=>{s=!0},self.perfMetrics.registerLCPCandidate=f,self.perfMetrics.inspectLCPTarget=()=>m})(addEventListener,removeEventListener,requestAnimationFrame);
// INP init code.
(function(a){var b=Math.max,c=Math.min;function d(){return null==t?null==performance.interactionCount?0:performance.interactionCount:u}function e(){const a=d()-n;return a}function f(){const a=c(r.length-1,Math.floor(e()/50));return r[a]}function g(){"PerformanceObserver"in window&&PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("event")&&(y(),m=new PerformanceObserver(a=>{Promise.resolve().then(()=>{const b=a.getEntries();i(b)})}),m.observe({type:"event",buffered:!0,durationThreshold:40}),m.observe({type:"first-input",buffered:!0}),a("visibilitychange",j,!0),a("pageshow",k,!0))}function h(a){if(null==a.interactionId)return;const c=r[r.length-1],d=s.get(a.interactionId);if(null!=d||r.length<q||a.duration>c.latency){if(null!=d)d.entries.push(a),d.latency=b(d.latency,a.duration);else{const b={id:a.interactionId,latency:a.duration,entries:[a]};r.push(b),s.set(a.interactionId,b)}r.sort((c,a)=>a.latency-c.latency),r.splice(q).forEach(a=>{s.delete(a.id)})}}function i(a){a.forEach(a=>{a.interactionId&&h(a)});const b=f();b&&b.latency!==o.value&&(o.value=b.latency,o.entries=b.entries,l())}function j(){null==m||"hidden"===document.visibilityState&&(i(m.takeRecords()),0>o.value&&0<e()&&(o.value=0,o.entries=[]),l())}function k(a){a.persisted&&(r=[],s.clear(),n=d(),o.value=-1,o.entries=[])}function l(){p&&p(o.value,o.entries)}let m,n=0;const o={value:-1,entries:[]};let p;const q=10;let r=[];const s=new Map;let t,u=0,v=1/0,w=0;const x=a=>{a.forEach(a=>{a.interactionId&&(v=c(v,a.interactionId),w=b(w,a.interactionId),u=w?(w-v)/7+1:0)})},y=()=>{"interactionCount"in performance||null!=t||PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("event")&&(t=new PerformanceObserver(a=>{Promise.resolve().then(()=>{x(a.getEntries())})}),t.observe({type:"event",buffered:!0,durationThreshold:0}))};g(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onInp=function(a){0<=o.value?a(o.value,o.entries):p=a},self.perfMetrics.clearInp=function(){r=[],s.clear(),n=0,u=0,v=1/0,w=0,o.value=-1,o.entries=[]}})(addEventListener);

In [34]:
ofertas = soup.find("div",{"class":"gsgwcjk"}).find_all("div",{"class":"t1jojoys"})
ofertas

[<div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_1114500207597778842">Habitación en Palma</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_5777364">Habitación en Palma</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_1123207961117123089">Habitación en Palma</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_1136925920193987967">Alojamiento en Palma</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_1008491119145244315">Habitación en Palma</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_1138172252912597886">Alojamiento en Palma</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_780201303870553973">Alojamiento en Palma</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_840469232177563046">Habitación en Palma</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_698491378882692671">Habitación en Palma</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_1080387255600240675">Apartamento en Santa Ponça</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_1137557575100171848">Apartamento en Palma</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_1134714032954665860">Minicasa en Santa Maria </div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_1091282966302026967">Apartamento en Illes Balears</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_1000558717850888612">Apartamento en Can Pastilla</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_920914924934463482">Vivienda en Can Pastilla</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_548218">Apartamento en Palma</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_1109459643095372445">Apartamento en Palma</div>,
 <div class="t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_9dzvea atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr" data-testid="listing-card-title" id="title_2290707">Apartamento en Palma</div>]

In [35]:
id = [oferta.get('id') for oferta in ofertas]
time.sleep(3)
apartament_id = [apartament for apartament in id if apartament is not None]
apartament_id

['title_1114500207597778842',
 'title_5777364',
 'title_1123207961117123089',
 'title_1136925920193987967',
 'title_1008491119145244315',
 'title_1138172252912597886',
 'title_780201303870553973',
 'title_840469232177563046',
 'title_698491378882692671',
 'title_1080387255600240675',
 'title_1137557575100171848',
 'title_1134714032954665860',
 'title_1091282966302026967',
 'title_1000558717850888612',
 'title_920914924934463482',
 'title_548218',
 'title_1109459643095372445',
 'title_2290707']

In [36]:
apartament_id = [apartament.replace("title_","") for apartament in apartament_id if apartament.startswith("title")]
apartament_id

['1114500207597778842',
 '5777364',
 '1123207961117123089',
 '1136925920193987967',
 '1008491119145244315',
 '1138172252912597886',
 '780201303870553973',
 '840469232177563046',
 '698491378882692671',
 '1080387255600240675',
 '1137557575100171848',
 '1134714032954665860',
 '1091282966302026967',
 '1000558717850888612',
 '920914924934463482',
 '548218',
 '1109459643095372445',
 '2290707']

In [37]:
len(apartament_id)

18

In [22]:
browser.close()

# 2. AUTOMATIZACIÓN IDs

In [14]:
from selenium.common.exceptions import NoSuchElementException

In [15]:
options = Options()
#options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
browser = webdriver.Chrome(options=options)

list_id=[]  #lista donde irán todos los ids unicos

#Definición de la fórmula

def get_ids(airbnb_urls):
    
    browser.get(airbnb_urls)
    time.sleep(2)

    pagina=0

    while pagina<15:
        if pagina<15:
            html=browser.page_source
            soup= bs(html, "lxml")
            id01= soup.find("div",{"class":"gsgwcjk"}).find_all("div",{"class":"t1jojoys"})
            id02= [id.get("id") for id in id01]   
            for x in id02:
                list_id.append(x.replace("title_",""))
            try:
                # Intenta hacer clic en el botón "Siguiente"
                browser.find_element("xpath", '//*[@aria-label="Siguiente"]').click()
            except NoSuchElementException:
                try:
                    # Si no se encuentra el botón "Siguiente", intenta hacer clic en el botón "Página siguiente"
                    browser.find_element("xpath", '//*[@aria-label="Página siguiente"]').click()
                except NoSuchElementException:
                    # Si no se encuentra ninguno de los botones, termina el bucle
                    break
            time.sleep(3)
            pagina= pagina + 1
        else:
            break

#Buscando por el Centro de Palma para tener más ofertas posible#
#Centro historico
airbnb_urls= "https://www.airbnb.es/s/CENTRO-HISTORICO--Palma--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=15.431300844727046&query=CENTRO%20HISTORICO%2C%20Palma%2C%20Espa%C3%B1a&place_id=ChIJ74yzfzqTlxIR5dma137h7GA&ne_lat=39.57853965722384&ne_lng=2.6571202492349357&sw_lat=39.56131764910217&sw_lng=2.6432024681753035&zoom=15.431300844727046&search_by_map=true"
get_ids(airbnb_urls)

#Zona Plaza España
airbnb_urls="https://www.airbnb.es/s/Plaza-Espa%C3%B1a--Plaza-de-Espa%C3%B1a--Palma--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=15.541524553505134&query=Plaza%20Espa%C3%B1a%2C%20Plaza%20de%20Espa%C3%B1a%2C%20Palma%2C%20Espa%C3%B1a&place_id=ChIJxT0wA1SSlxIRT_KCBPb1tlg&ne_lat=39.58460662230665&ne_lng=2.660788597428848&sw_lat=39.56865293162735&sw_lng=2.647894547197552&zoom=15.541524553505134&search_by_map=true"
get_ids(airbnb_urls)

#Zona Puerto (Sur)
airbnb_urls="https://www.airbnb.es/s/Puerto-de-Palma-de-Mallorca--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=14.623465724603745&query=Puerto%20de%20Palma%20de%20Mallorca%2C%20Espa%C3%B1a&place_id=ChIJ2aHIoROSlxIRwXG9ScrlCyY&ne_lat=39.58206536139332&ne_lng=2.6476976771561738&sw_lat=39.551915536918436&sw_lng=2.623333452069261&zoom=14.623465724603745&search_by_map=true"
get_ids(airbnb_urls)

#Zona Norte
airbnb_urls="https://www.airbnb.es/s/Distrito-norte-de-Palma--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Distrito%20norte%20de%20Palma%2C%20Espa%C3%B1a&place_id=ChIJBxpQnlqSlxIRSUWz8SJUC1w&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&ne_lat=39.61455224432677&ne_lng=2.669565868791551&sw_lat=39.57402748046394&sw_lng=2.6368047002708295&zoom=14.196243246680217&zoom_level=14.196243246680217&search_by_map=true"
get_ids(airbnb_urls)

#Zona Oeste
airbnb_urls="https://www.airbnb.es/s/Distrito-Centro--Palma--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Distrito%20Centro%2C%20Palma%2C%20Espa%C3%B1a&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=14.633493246680196&place_id=ChIJBxpQnlqSlxIRSUWz8SJUC1w&ne_lat=39.58517553392277&ne_lng=2.6795036276431574&sw_lat=39.55523592907729&sw_lng=2.655308160129948&zoom=14.633493246680196&search_by_map=true"
get_ids(airbnb_urls)

#Zona Este
airbnb_urls="https://www.airbnb.es/s/Distrito-Centro--Palma--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Distrito%20Centro%2C%20Palma%2C%20Espa%C3%B1a&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=14.419868246680196&place_id=ChIJBxpQnlqSlxIRSUWz8SJUC1w&ne_lat=39.58239788135792&ne_lng=2.6354252175987654&sw_lat=39.54767738199466&sw_lng=2.607368197004263&zoom=14.419868246680196&search_by_map=true"
get_ids(airbnb_urls)

#Zona Es Molinar
airbnb_urls="https://www.airbnb.es/s/El-Molinar--Palma--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=14.068474092821702&query=El%20Molinar%2C%20Palma%2C%20Espa%C3%B1a&place_id=ChIJkZ9xAMCTlxIREBYW4w8Uu8s&ne_lat=39.58934740541659&ne_lng=2.6955241456443844&sw_lat=39.5450526212005&sw_lng=2.6597291979984448&zoom=14.068474092821702&search_by_map=true"
get_ids(airbnb_urls)


browser.close()

ElementClickInterceptedException: Message: element click intercepted: Element <a aria-label="Siguiente" href="/s/Plaza-España--Plaza-de-España--Palma--España/homes?tab_id=home_tab&amp;refinement_paths%5B%5D=%2Fhomes&amp;flexible_trip_lengths%5B%5D=one_week&amp;monthly_start_date=2024-05-01&amp;monthly_length=3&amp;monthly_end_date=2024-08-01&amp;price_filter_input_type=0&amp;channel=EXPLORE&amp;date_picker_type=calendar&amp;source=structured_search_input_header&amp;search_type=user_map_move&amp;price_filter_num_nights=5&amp;zoom_level=14&amp;query=Plaza%20Espa%C3%B1a%2C%20Plaza%20de%20Espa%C3%B1a%2C%20Palma%2C%20Espa%C3%B1a&amp;place_id=ChIJxT0wA1SSlxIRT_KCBPb1tlg&amp;ne_lat=39.58436990560867&amp;ne_lng=2.661552360014383&amp;sw_lat=39.555766962850235&amp;sw_lng=2.6336615258472023&amp;zoom=14.068064573244705&amp;search_by_map=true&amp;federated_search_session_id=8409cc38-14b8-4b51-b8d9-ecdb151a1372&amp;pagination_search=true&amp;cursor=eyJzZWN0aW9uX29mZnNldCI6MiwiaXRlbXNfb2Zmc2V0IjoxOCwidmVyc2lvbiI6MX0%3D" class="l1ovpqvx atm_1he2i46_1k8pnbi_10saat9 atm_yxpdqi_1pv6nv4_10saat9 atm_1a0hdzc_w1h1e8_10saat9 atm_ywwsz3_1afjdsa_10saat9 atm_1lnvhrj_zhgkwc_10saat9 atm_8i46q5_63ecz1_10saat9 c1ytbx3a atm_mk_h2mmj6 atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_bb_idpfg4 atm_26_1j28jx2 atm_3f_glywfm atm_7l_hkljqm atm_gi_idpfg4 atm_l8_idpfg4 atm_uc_10d7vwn atm_kd_glywfm atm_gz_8tjzot atm_uc_glywfm__1rrf6b5 atm_26_zbnr2t_1rqz0hn_uv4tnr atm_tr_kv3y6q_csw3t1 atm_26_zbnr2t_1ul2smo atm_3f_glywfm_jo46a5 atm_l8_idpfg4_jo46a5 atm_gi_idpfg4_jo46a5 atm_3f_glywfm_1icshfk atm_kd_glywfm_19774hq atm_70_glywfm_1w3cfyq atm_uc_aaiy6o_9xuho3 atm_70_18bflhl_9xuho3 atm_26_zbnr2t_9xuho3 atm_uc_glywfm_9xuho3_1rrf6b5 atm_70_glywfm_pfnrn2_1oszvuo atm_uc_aaiy6o_1buez3b_1oszvuo atm_70_18bflhl_1buez3b_1oszvuo atm_26_zbnr2t_1buez3b_1oszvuo atm_uc_glywfm_1buez3b_1o31aam atm_7l_1wxwdr3_1o5j5ji atm_9j_13gfvf7_1o5j5ji atm_26_1j28jx2_154oz7f atm_92_1yyfdc7_vmtskl atm_9s_1ulexfb_vmtskl atm_mk_stnw88_vmtskl atm_tk_1ssbidh_vmtskl atm_fq_1ssbidh_vmtskl atm_tr_pryxvc_vmtskl atm_vy_1vi7ecw_vmtskl atm_e2_1vi7ecw_vmtskl atm_5j_1ssbidh_vmtskl atm_mk_h2mmj6_1ko0jae dir dir-ltr">...</a> is not clickable at point (435, 486). Other element would receive the click: <a href="/help/community?s=footer" class="l1ovpqvx atm_1he2i46_1k8pnbi_10saat9 atm_yxpdqi_1pv6nv4_10saat9 atm_1a0hdzc_w1h1e8_10saat9 atm_ywwsz3_1afjdsa_10saat9 atm_1lnvhrj_zhgkwc_10saat9 atm_8i46q5_63ecz1_10saat9 c1kblhex atm_1s_glywfm atm_26_1j28jx2 atm_3f_idpfg4 atm_9j_tlke0l atm_gi_idpfg4 atm_l8_idpfg4 atm_vb_1wugsn5 atm_rd_glywfm atm_c8_km0zk7 atm_g3_18khvle atm_fr_1m9t47k atm_7l_dezgoh atm_cs_6adqpa atm_kd_glywfm atm_9j_13gfvf7_1o5j5ji atm_rd_glywfm_1mj13j2_uv4tnr atm_rd_8stvzk_1nos8r atm_3f_glywfm_jo46a5 atm_l8_idpfg4_jo46a5 atm_gi_idpfg4_jo46a5 atm_3f_glywfm_1icshfk atm_kd_glywfm_19774hq atm_7l_1ulhtn1_pfnrn2 atm_rd_8stvzk_pfnrn2 atm_uc_ryfd4z_pfnrn2 atm_5j_yh40bf_pfnrn2 atm_70_pd3o52_pfnrn2 atm_uc_glywfm_pfnrn2_1rrf6b5 dir dir-ltr">...</a>
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6762A1522+60802]
	(No symbol) [0x00007FF67621AC22]
	(No symbol) [0x00007FF6760D7CE4]
	(No symbol) [0x00007FF67612E877]
	(No symbol) [0x00007FF67612C344]
	(No symbol) [0x00007FF67612980A]
	(No symbol) [0x00007FF6761289E2]
	(No symbol) [0x00007FF67611AE8B]
	(No symbol) [0x00007FF67614AB7A]
	(No symbol) [0x00007FF67611A7C6]
	(No symbol) [0x00007FF67614AD90]
	(No symbol) [0x00007FF67616A224]
	(No symbol) [0x00007FF67614A923]
	(No symbol) [0x00007FF676118FEC]
	(No symbol) [0x00007FF676119C21]
	GetHandleVerifier [0x00007FF6765A413D+3217821]
	GetHandleVerifier [0x00007FF6765E60D7+3488055]
	GetHandleVerifier [0x00007FF6765DF05F+3459263]
	GetHandleVerifier [0x00007FF67635B866+823494]
	(No symbol) [0x00007FF676225FBF]
	(No symbol) [0x00007FF676220EE4]
	(No symbol) [0x00007FF676221072]
	(No symbol) [0x00007FF6762118C4]
	BaseThreadInitThunk [0x00007FFF44A0257D+29]
	RtlUserThreadStart [0x00007FFF4562AA48+40]

## Eliminar duplicados

In [30]:
lista_id_set= list (set(list_id))
lista_ids= list(lista_id_set)
print(len(lista_ids))

753

In [ ]:
#Consideramos que para tener una analizis representativa, nesesitamos más datos. 
#Nuestra idea es tener unos 2000 ofertas de cada destino
#Decidimos añadir otras ciudades populares de Mallorca

## AUTOMATIZAR OTRAS CIUDADES / IDs

In [40]:
options = Options()
#options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
browser = webdriver.Chrome(options=options)

list_id=[]  #lista donde irán todos los ids unicos

#Definición de la fórmula

def get_ids(airbnb_urls):
    
    browser.get(airbnb_urls)
    time.sleep(2)

    pagina=0

    while pagina<15:
        if pagina<15:
            html=browser.page_source
            soup= bs(html, "lxml")
            id01= soup.find("div",{"class":"gsgwcjk"}).find_all("div",{"class":"t1jojoys"})
            id02= [id.get("id") for id in id01]   
            for x in id02:
                list_id.append(x.replace("title_",""))
            try:
                # Intenta hacer clic en el botón "Siguiente"
                browser.find_element("xpath", '//*[@aria-label="Siguiente"]').click()
            except NoSuchElementException:
                try:
                    # Si no se encuentra el botón "Siguiente", intenta hacer clic en el botón "Página siguiente"
                    browser.find_element("xpath", '//*[@aria-label="Página siguiente"]').click()
                except NoSuchElementException:
                    # Si no se encuentra ninguno de los botones, termina el bucle
                    break
            time.sleep(3)
            pagina= pagina + 1
        else:
            break

#Buscando ciudades más visitadas en Mallorca (isla entera)#
#Playa de Palma
airbnb_urls= "https://www.airbnb.es/s/Playa-de-Palma--Mallorca--Carretera-de-s%E2%80%99Arenal--Palma--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Playa%20de%20Palma%2C%20Mallorca%2C%20Carretera%20de%20s%E2%80%99Arenal%2C%20Palma%2C%20Espa%C3%B1a&place_id=ChIJa7Ry2qKXlxIRQQLoXPUaAiU&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&ne_lat=39.57382420916327&ne_lng=2.7680315912912477&sw_lat=39.473265312530955&sw_lng=2.702155485788694&zoom=12.88654934751744&zoom_level=12.88654934751744&search_by_map=true"
get_ids(airbnb_urls)

#Magaluf
airbnb_urls="https://www.airbnb.es/s/Magaluf--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Magaluf%2C%20Espa%C3%B1a&place_id=ChIJ7eFDwDaJlxIRYEJXf3GvAgo&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&ne_lat=39.56856776096179&ne_lng=2.5623829107717313&sw_lat=39.483225816783545&sw_lng=2.506473537793255&zoom=13.123214449828561&zoom_level=13.123214449828561&search_by_map=true"
get_ids(airbnb_urls)

#Paguera
airbnb_urls="https://www.airbnb.es/s/Peguera--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Peguera%2C%20Espa%C3%B1a&place_id=ChIJBfP4FU4nmBIR4EFXf3GvAgo&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&ne_lat=39.59957989872353&ne_lng=2.4853826191504993&sw_lat=39.469371456010215&sw_lng=2.4000696569322884&zoom=12.513539657776601&zoom_level=12.513539657776601&search_by_map=true"
get_ids(airbnb_urls)

#Valldemossa
airbnb_urls="https://www.airbnb.es/s/Valldemosa--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Valldemosa%2C%20Espa%C3%B1a&place_id=ChIJG4cMDP3xlxIRL6NICVu0GMs&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&ne_lat=39.75121498496401&ne_lng=2.653493653063947&sw_lat=39.66211428849414&sw_lng=2.594969197784195&zoom=13.05726501369674&zoom_level=13.05726501369674&search_by_map=true"
get_ids(airbnb_urls)

#Cala D´Or
airbnb_urls="https://www.airbnb.es/s/Cala-d'Or--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Cala%20d%27Or%2C%20Espa%C3%B1a&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=14.183227685836505&place_id=ChIJu0joY8NQlhIRAEFXf3GvAgo&ne_lat=39.39831330737082&ne_lng=3.244772131855001&sw_lat=39.357293786505835&sw_lng=3.217956450160557&zoom=14.183227685836505&search_by_map=true"
get_ids(airbnb_urls)

#Cala Millor
airbnb_urls="https://www.airbnb.es/s/Cala-Millor--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Cala%20Millor%2C%20Espa%C3%B1a&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=13.795672707330466&place_id=ChIJu43fX39AlhIRoEFXf3GvAgo&ne_lat=39.62499385701601&ne_lng=3.3980735884207434&sw_lat=39.571503018573154&sw_lng=3.362993997893085&zoom=13.795672707330466&search_by_map=true"
get_ids(airbnb_urls)

#Cala Ratjada
airbnb_urls="https://www.airbnb.es/s/Cala-Rajada--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Cala%20Rajada%2C%20Espa%C3%B1a&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=13.396746226412718&place_id=ChIJde3StVgWlhIRYQHEEMePNXE&ne_lat=39.7482242569394&ne_lng=3.486472852272641&sw_lat=39.67781218674761&sw_lng=3.440219485314344&zoom=13.396746226412718&search_by_map=true"
get_ids(airbnb_urls)

#Puerto de Alcudia
airbnb_urls="https://www.airbnb.es/s/Puerto-de-Alcudia--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Puerto%20de%20Alcudia%2C%20Espa%C3%B1a&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=14.696786929705514&place_id=ChIJdbn7RIkslhIRSmUHuNeXkwQ&ne_lat=39.84747271334752&ne_lng=3.135397317662921&sw_lat=39.818927213044724&sw_lng=3.116613143559647&zoom=14.696786929705514&search_by_map=true"
get_ids(airbnb_urls)

#Playa de Muro
airbnb_urls="https://www.airbnb.es/s/Playa-de-Muro--Muro--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Playa%20de%20Muro%2C%20Muro%2C%20Espa%C3%B1a&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=14.214217539233625&place_id=ChIJcSz5-3gtlhIRgt5VOlgav2E&ne_lat=39.829303411119426&ne_lng=3.1694506472994988&sw_lat=39.7887227169762&sw_lng=3.0765966900841875&zoom=14.214217539233625&search_by_map=true"
get_ids(airbnb_urls)

#Can Picafort
airbnb_urls="https://www.airbnb.es/s/Can-Picafort--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Can%20Picafort%2C%20Espa%C3%B1a&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=14.618597176974376&place_id=ChIJ99Zo7XsylhIR4NW0vjHkM5c&ne_lat=39.78302628348756&ne_lng=3.163916007385552&sw_lat=39.75286240125&sw_lng=3.1440856945365567&zoom=14.618597176974376&search_by_map=true"
get_ids(airbnb_urls)

#Puerto de Pollenca
airbnb_urls="https://www.airbnb.es/s/Pollensa--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2024-05-01&monthly_length=3&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Pollensa%2C%20Espa%C3%B1a&date_picker_type=calendar&source=structured_search_input_header&search_type=user_map_move&price_filter_num_nights=5&zoom_level=14.328894759105863&place_id=ChIJw5BMUeXUlxIRcAAi126vAgQ&ne_lat=39.91410709110692&ne_lng=3.090862752645336&sw_lat=39.87730363654517&sw_lng=3.0666224139639837&zoom=14.328894759105863&search_by_map=true"
get_ids(airbnb_urls)

browser.close()

In [41]:
lista_id_set2= list (set(list_id))
lista_ids2= list(lista_id_set2)
print(len(lista_ids2))

2076

## Juntar en una lista

In [16]:
ids_palma_juntar = lista_ids + lista_ids2

NameError: name 'lista_ids' is not defined

In [45]:
ids_palma_set = list(set(ids_palma_juntar))
ids_palma = list(ids_palma_set)
print(len(ids_palma))

2829

## Crear DF y guardar en CSV / IDs

In [46]:
ids_pmi = pd.DataFrame(ids_palma, columns=['ID'])
ids_pmi.head(5)

                   ID
0  597803129034496102
1            14410604
2            40630146
3            34015728
4  967142928539935593

In [47]:
ids_pmi.to_csv('ids_pmi_23.04.csv',index = False)

# 3. AUTOMATIZACION DATOS

In [23]:
lista_idsx = pd.read_csv("C:\\Users\\Usuario\\OneDrive\\Documentos\\Master Data Analytics\\Proyecto Júpiter\\Datasets\\ids_pmi_23.04.csv")['ID'].tolist()

In [ ]:
options = Options()
#options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
browser = webdriver.Chrome(options=options)

url = "https://www.airbnb.es/s/Mallorca--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Mallorca%2C%20Espa%C3%B1a&place_id=ChIJKcEGZna4lxIRwOzSAv-b67c&date_picker_type=calendar&source=structured_search_input_header&search_type=filter_change&price_filter_num_nights=6"
browser.get(url)
time.sleep(3)

lista_titulos=[]
lista_tipo_hab=[]
lista_valoracion=[]
lista_num_valoracion=[]
lista_ciudad=[]
lista_baño=[]
lista_dormitorios=[]
lista_camas=[]
lista_viajeros=[]
lista_precios_oct=[]
lista_precios_ago=[]

for x in lista_idsx:
    url_hab = f"https://www.airbnb.es/rooms/{x}"
    url_hab_ago= f"https://www.airbnb.es/rooms/{x}?source_impression_id=p3_1713604628_Lgj1zTSBQ4yrgaUA&check_in=2024-08-12&guests=1&adults=1&check_out=2024-08-18"
    url_hab_oct= f"https://www.airbnb.es/rooms/{x}?source_impression_id=p3_1713604628_Lgj1zTSBQ4yrgaUA&check_in=2024-10-14&guests=1&adults=1&check_out=2024-10-20"

    #HTML PRINCIPAL DEL HOST MALLORCA SIN FECHA
    browser.get(url_hab)
    time.sleep(2)
    try:
        browser.find_element("xpath", '//*[@aria-label="Cerrar"]').click()
    except:
        pass
    html=browser.page_source
    soup= bs(html, "lxml")

    #HTML PRINCIPAL DEL HOST EN AGOSTO
    browser.get(url_hab_ago)
    time.sleep(2)
    try:
        browser.find_element("xpath", '//*[@aria-label="Cerrar"]').click()
    except:
        pass
    html=browser.page_source
    soup_ago= bs(html, "lxml")

    #HTML PRINCIPAL DEL HOST EN OCTUBRE
    browser.get(url_hab_oct)
    time.sleep(2)
    try:
        browser.find_element("xpath", '//*[@aria-label="Cerrar"]').click()
    except:
        pass
    html=browser.page_source
    soup_oct= bs(html, "lxml")

    #TITULO
    titulos= soup.find("h1",{"elementtiming":"LCP-target"})
    if titulos is None:
        lista_titulos.append(None)
    else:
        lista_titulos.append(titulos.text.strip())

    #TIPO HAB
    tipo_hab= soup.find("h2",{"elementtiming":"LCP-target"})
    if tipo_hab is None:
        lista_tipo_hab.append(None)
    else: 
        lista_tipo_hab.append(tipo_hab.text.strip())

    #VALORACION
    valoracion= soup.find("div", {"class":"r1lutz1s"})
    if valoracion is None:
        lista_valoracion.append("Sin valoraciones")
    else:
        lista_valoracion.append(valoracion.text.strip())

    #NUMERO VALORACIONES
    num_valoraciones= soup.find("a",{"class":"l1ovpqvx atm_1he2i46_1k8pnbi_10saat9 atm_yxpdqi_1pv6nv4_10saat9 atm_1a0hdzc_w1h1e8_10saat9 atm_ywwsz3_1afjdsa_10saat9 atm_1lnvhrj_zhgkwc_10saat9 atm_8i46q5_63ecz1_10saat9 b1uxatsa atm_c8_1kw7nm4 atm_bx_1kw7nm4 atm_cd_1kw7nm4 atm_ci_1kw7nm4 atm_g3_1kw7nm4 atm_9j_tlke0l_1nos8r_uv4tnr atm_7l_1kw7nm4_pfnrn2 atm_rd_8stvzk_pfnrn2 c1qih7tm atm_1s_glywfm atm_26_1j28jx2 atm_3f_idpfg4 atm_9j_tlke0l atm_gi_idpfg4 atm_l8_idpfg4 atm_vb_1wugsn5 atm_7l_jt7fhx atm_rd_8stvzk atm_5j_1896hn4 atm_cs_9dzvea atm_r3_1kw7nm4 atm_mk_h2mmj6 atm_kd_glywfm atm_9j_13gfvf7_1o5j5ji atm_7l_jt7fhx_v5whe7 atm_rd_8stvzk_v5whe7 atm_7l_177r58q_1nos8r_uv4tnr atm_rd_8stvzk_1nos8r_uv4tnr atm_7l_9vytuy_4fughm_uv4tnr atm_rd_8stvzk_4fughm_uv4tnr atm_rd_8stvzk_xggcrc_uv4tnr atm_7l_1he744i_csw3t1 atm_rd_8stvzk_csw3t1 atm_3f_glywfm_jo46a5 atm_l8_idpfg4_jo46a5 atm_gi_idpfg4_jo46a5 atm_3f_glywfm_1icshfk atm_kd_glywfm_19774hq atm_7l_jt7fhx_1w3cfyq atm_rd_8stvzk_1w3cfyq atm_uc_aaiy6o_1w3cfyq atm_70_1p56tq7_1w3cfyq atm_uc_glywfm_1w3cfyq_1rrf6b5 atm_7l_jt7fhx_pfnrn2_1oszvuo atm_rd_8stvzk_pfnrn2_1oszvuo atm_uc_aaiy6o_pfnrn2_1oszvuo atm_70_1p56tq7_pfnrn2_1oszvuo atm_uc_glywfm_pfnrn2_1o31aam atm_7l_9vytuy_1o5j5ji atm_rd_8stvzk_1o5j5ji atm_rd_8stvzk_1mj13j2 dir dir-ltr"})
    if num_valoraciones is None:
        lista_num_valoracion.append("Sin valoraciones")
    else:
        lista_num_valoracion.append(num_valoraciones.text.strip())
    
    #PRECIOS OCTUBRE
    precios_oct= soup_oct.find("span",{"class":"_1y74zjx"})
    if precios_oct is None:
        lista_precios_oct.append("No disponible en Octubre")
    else:
        lista_precios_oct.append(precios_oct.text.replace("\xa0"," ").replace("€", "").strip())
        pass

    #PRECIOS AGOSTO
    precios_ago= soup_ago.find("span",{"class":"_1y74zjx"})
    if precios_ago is None:
        lista_precios_ago.append("No disponible en Agosto")
    else:
        lista_precios_ago.append(precios_ago.text.replace("\xa0"," ").replace("€", "").strip())
        pass

    #CIUDAD
    lista_ciudad.append("Mallorca")

    #BAÑO
    otros= soup_oct.find("ol", {"class":"lgx66tx"})
    if otros is None:
        otros=None
        lista_baño.append(None)
    else:
        otros= otros.text.lower()
        if "baño compartido" in otros:
            index= otros.find("baño")
            lista_baño.append(otros[index:].strip())
        elif "baño" in otros:
            index= otros.find("baño")
            lista_baño.append(otros[index -2:].strip())
        else:
            lista_baño.append("Sin baños")

    #DORMITORIOS
    if otros is None:
        lista_dormitorios.append(None)
    else:
        if "dormirtorio" in otros:
            index= otros.find("dormitorio")
            lista_dormitorios.append(otros[index -2: index + 10].strip())
        elif "dormitorios" in otros:
            index= otros.find("dormitorios")
            lista_dormitorios.append(otros[index -2:index + 11].strip())
        else:
            lista_dormitorios.append("1 dormitorio")

    #CAMAS
    if otros is None:
        lista_camas.append(None)
    else:
        if "cama" in otros:
            index= otros.find("cama")
            lista_camas.append(otros[index -2: index + 5].strip())
        elif "camas" in otros:
            index= otros.find("camas")
            lista_camas.append(otros[index -2: index + 6].strip())
        else:
            lista_camas.append("No especificado")

    #VIAJEROS
    if otros is None:
        lista_viajeros.append(None)
    else:
        if "viajero" in otros:
            index= otros.find("viajero")
            lista_viajeros.append(otros[index -2: index + 8].replace("\xa0"," ").strip())
        elif "viajeros" in otros:
            index= otros.find("viajeros")
            lista_viajeros.append(otros[index -2: index + 9].replace("\xa0"," ").strip())
        else:
            lista_viajeros.append("No especificado")

browser.close()

## Crear DF y guardar en CSV / DATOS

In [27]:
airbnb_pmi= pd.DataFrame({"ID":lista_idsx, "Tipo de habitación":lista_tipo_hab, "Ciudad":lista_ciudad,"Precio por noche Agosto":lista_precios_ago,"Precio por noche Octubre":lista_precios_oct, "Valoración":lista_valoracion, "Numero valoraciones": lista_num_valoracion, "Dormitorios":lista_dormitorios, "Baños":lista_baño, "Camas":lista_camas,"Viajeros máximos":lista_viajeros})
airbnb_pmi.to_csv("airbnb_pmi.csv")

In [28]:
airbnb_pmi.head(10)

,ID,Tipo de habitación,Ciudad,Precio por noche Agosto,Precio por noche Octubre,Valoración,Numero valoraciones,Dormitorios,Baños,Camas,Viajeros máximos
0,597803129034496102,"Caravana/autocaravana en Palma, España",Mallorca,No disponible en Agosto,65 €,"5,0",4 evaluaciones,1 dormitorio,0 baños,2 camas,2 viajeros
1,14410604,"Alojamiento entero: vivienda en Palma, España",Mallorca,No disponible en Agosto,217 €,"4,89",44 evaluaciones,3 dormitorios,5 baños,3 camas,5 viajeros
2,40630146,"Habitación en Palma, España",Mallorca,106,100 €,"4,83",24 evaluaciones,1 dormitorio,· baño privado en la habitación,1 cama,No especificado
3,34015728,"Alojamiento entero: piso en Illes Balears, España",Mallorca,No disponible en Agosto,93 €,"4,80",15 evaluaciones,1 dormitorio,1 baño,2 camas,3 viajeros
4,967142928539935593,"Alojamiento entero: piso en Palma, España",Mallorca,No disponible en Agosto,No disponible en Octubre,Sin valoraciones,1 evaluación,1 dormitorio,1 baño,No especificado,2 viajeros
5,569887893897108746,"Alojamiento entero: piso en Can Picafort, España",Mallorca,No disponible en Agosto,98 €,Sin valoraciones,1 evaluación,2 dormitorios,1 baño,4 camas,5 viajeros
6,822981985426892644,"Alojamiento entero: villa en Provensals, España",Mallorca,No disponible en Agosto,No disponible en Octubre,"4,43",7 evaluaciones,4 dormitorios,5 baños,1 cama,6 viajeros
7,1047216,"Alojamiento entero: adosado en Can Picafort, E...",Mallorca,233,102 €,Sin valoraciones,Mostrar másMostrar más. Abre el perfil del anf...,2 dormitorios,2 baños,3 camas,4 viajeros
8,7716138,Alojamiento entero: apartamento con servicios ...,Mallorca,No disponible en Agosto,90 €,"4,58",95 evaluaciones,2 dormitorios,2 baños,5 camas,4 viajeros
9,1037505297649838255,"Habitación en Palma, España",Mallorca,150,100 €,Sin evaluaciones,Política de Cookies,1 dormitorio,· baño privado en la habitación,1 cama,No especificado

In [32]:
airbnb_pmi.shape

(2829, 11)

# 4. AUTOMATIZACIÓN LISTA DE AMENETIES

#*pending*

In [ ]:
options = Options()
#options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
browser = webdriver.Chrome(options=options)

url = "https://www.airbnb.es/s/Mallorca--Espa%C3%B1a/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_end_date=2024-08-01&price_filter_input_type=0&channel=EXPLORE&query=Mallorca%2C%20Espa%C3%B1a&place_id=ChIJKcEGZna4lxIRwOzSAv-b67c&date_picker_type=calendar&source=structured_search_input_header&search_type=filter_change&price_filter_num_nights=6"
browser.get(url)
time.sleep(3)

lista_amenities=[]

for x in lista_idsx:
    url_hab_ame= f"https://www.airbnb.es/rooms/{x}/amenities?source_impression_id=p3_1713604628_Lgj1zTSBQ4yrgaUA&check_in=2024-10-14&guests=1&adults=1&check_out=2024-10-20"

    #HTML AMENITIES DEL HOST
    browser.get(url_hab_ame)
    sleep(2)
    html_ame=browser.page_source
    soup_ame= bs(html_ame, "lxml")

    #AMENITIES
    amenities01 = soup_ame.find('div',{'class':'_17itzz4'})
    if amenities01 is None:
        lista_amenities.append(None)
    else:
        lista_amenities.append([i.text.strip() for i in amenities01.find_all('li')])

browser.close()